import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getDashboardModel } from './dashboardModel.js';
import './dashboard.css';

export function PreparationDashboard({state,legacyState,language='zh'}) {
  const en = language === 'en';
  const t = (zh,english) => en ? english : zh;
  const [now,setNow] = useState(() => new Date());
  useEffect(() => { const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer); },[]);
  const model = useMemo(()=>getDashboardModel(state,legacyState,now),[state,legacyState,now]);
  const {todaySummary:today,dailyProgress:progress,activeSession:session} = model;
  const dailyHref = session ? `/daily-mock?session=${encodeURIComponent(session.id)}` : '/daily-mock';
  const maxCount = Math.max(1,...model.week.map(day => day.totalQuestions));
  const metrics = [[t('量化题','Quant'),today.quant],[t('速算正确题','Mental math'),today.mental],[t('技术题','Tech'),today.tech],['Coding OA',today.coding],['Behavioral',today.behavioral]];
  return <div className="prep-dashboard">
    <header className="prep-dashboard-heading"><div><p className="prep-eyebrow">{now.toLocaleDateString(en?'en-US':'zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</p><h1>{t('今日备战','Your preparation today')}</h1><p>{t('从上次停下的地方继续。','Pick up where you left off.')}</p></div><Link className="prep-link" to="/calendar">{t('查看训练日历','View calendar')} →</Link></header>
    <div className="prep-priority-grid">
      <section className="prep-next-session" aria-labelledby="prep-next-title"><p className="prep-eyebrow">DAILY MOCK</p><h2 id="prep-next-title">{session ? t('继续这一轮训练','Continue your session') : t('开始今天的练习','Start today’s practice')}</h2><p>{session ? t(`已完成 ${progress.completed} / ${progress.total} 项，题目和草稿已保留。`,`${progress.completed} of ${progress.total} items complete. Your questions and drafts are retained.`) : t('速算、技术面试、Coding OA 与行为面试。题量和时间由你调整。','Mental math, technical questions, coding and behavioral practice. Set your own question counts and time budgets.')}</p>{session && <progress max={progress.total || 1} value={progress.completed} aria-label={t('本轮完成进度','Session progress')}/>}<Link className="prep-solid-link" to={dailyHref}>{session ? t('继续训练','Continue training') : t('配置并开始','Configure & start')} →</Link><small>{session ? t(`开始于 ${session.dateKey}`,`Started ${session.dateKey}`) : t('可以分次完成，离开后继续。','Complete it in stages, at your own pace.')}</small></section>
      <section className="prep-review-preview" aria-labelledby="prep-review-title"><div className="prep-panel-heading"><h2 id="prep-review-title">{t('今天要复习','Due for review')}</h2><span>{model.dueReviews.length}</span></div>{model.dueReviews.length ? <ul>{model.dueReviews.slice(0,3).map(item=><li key={item.questionKey}><Link to={`/review?question=${encodeURIComponent(item.questionKey)}`}>{en ? item.question.titleEn || item.question.title : item.question.title}<span>{item.question.kind === 'coding' ? 'Coding OA' : item.question.kind === 'behavioral' ? 'Behavioral' : 'Tech interview'}</span></Link></li>)}</ul> : <div className="prep-quiet-empty"><strong>{t('目前没有到期题目','No reviews due')}</strong><p>{t('Daily Mock 中标记“需要复习”或“借助提示完成”的题目会出现在这里。','Questions marked “Needs review” or “With help” in Daily Mock appear here.')}</p></div>}<Link className="prep-link" to="/review">{t('打开复习队列','Open review queue')} →</Link></section>
    </div>
    <section className="prep-today-summary" aria-labelledby="prep-today-title"><div className="prep-panel-heading"><h2 id="prep-today-title">{t('今天已经完成','Completed today')}</h2><span>{t(`${today.daily} 轮 Daily Mock`,`${today.daily} daily mocks`)}</span></div><dl>{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}<small>{t('题','questions')}</small></dd></div>)}</dl></section>
    <div className="prep-detail-grid">
      <section className="prep-week-panel" aria-labelledby="prep-week-title"><div className="prep-panel-heading"><h2 id="prep-week-title">{t('最近七天','Last seven days')}</h2><span>{model.weekActiveDays} / 7 {t('天有训练','active days')}</span></div><div className="prep-week-bars" aria-label={t('每日完成题数','Daily completed question counts')}>{model.week.map(day=><Link key={day.key} to={`/calendar?date=${day.key}`} aria-label={`${day.key}: ${day.totalQuestions} ${t('题','questions')}`}><strong>{day.totalQuestions}</strong><span className="prep-week-bar-track"><span style={{height:`${day.totalQuestions / maxCount * 100}%`}}/></span><small>{day.key.slice(5).replace('-','/')}</small></Link>)}</div><p className="prep-caption">{t('按实际完成记录统计；速算只计正确作答。','Based on completed records; mental math counts correct answers.')}</p></section>
      <section className="prep-upcoming-panel" aria-labelledby="prep-upcoming-title"><div className="prep-panel-heading"><h2 id="prep-upcoming-title">{t('申请的下一步','Next application steps')}</h2><Link className="prep-link" to="/applications">{t('全部申请','All applications')} →</Link></div>{model.upcoming.length ? <ul>{model.upcoming.slice(0,4).map(item=><li key={item.id}><Link to={`/applications?application=${encodeURIComponent(item.id)}`}><div><strong>{item.company}</strong><span>{item.upcomingKind === "deadline" ? t(`申请截止 · ${item.role}`,`Application deadline · ${item.role}`) : item.nextAction || item.role}</span></div><small className={item.overdue?'is-overdue':''}>{item.overdue ? t('已逾期 · ','Overdue · ') : ''}{item.upcomingDate}</small></Link></li>)}</ul> : <div className="prep-quiet-empty"><strong>{t('为申请安排下一步','Plan your next step')}</strong><p>{t('保存目标岗位、申请状态与截止日期，把 OA 和面试准备放进你的日程。','Save target roles, stages and deadlines to keep assessments and interviews in view.')}</p><Link className="prep-link" to="/applications">{t('记录一条申请','Add an application')} →</Link></div>}</section>
    </div>
    <section className="prep-mental-summary" aria-labelledby="prep-mental-title"><div><p className="prep-eyebrow">MENTAL MATH</p><h2 id="prep-mental-title">{model.latestTrial ? t(`上次完成 ${model.latestTrial.correct} 题`,`Last trial: ${model.latestTrial.correct} correct`) : t('保持你的速算节奏','Build your mental math rhythm')}</h2><p>{model.latestTrial ? t(`同样设置的最高纪录：${model.mentalBest} 题。查看逐题耗时，找到慢题。`,`Best with the same settings: ${model.mentalBest} correct. Review per-question timing to find slower questions.`) : t('每道题的用时、最近几轮的变化，以及同设置下的个人纪录。','Track each question, compare recent trials and measure your best with the same settings.')}</p></div><Link className="prep-outline-link" to="/tools">{t('开始速算','Practice mental math')} →</Link></section>
  </div>;
}
