#!/usr/bin/env python3
"""Validate local readiness for a future SQLite -> Postgres cutover.

This does not connect to Postgres or migrate production data. It verifies that
the checked-in Postgres DDL mirrors the current SQLite API schema, and that the
current SQLite data shape can be exported safely when a real cutover is planned.
"""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import os
import re
import sqlite3
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB = PROJECT_ROOT / "api-server" / "data" / "quantgym.sqlite3"
DEFAULT_SCHEMA = PROJECT_ROOT / "api-server" / "postgres" / "schema.sql"

JSON_COLUMNS = {
    "account_json",
    "state_json",
    "community_json",
    "metadata_json",
    "problem_json",
    "room_json",
    "tags_json",
}

TIMESTAMP_COLUMNS = {
    "created_at",
    "updated_at",
    "sent_at",
    "expires_at",
    "consumed_at",
    "archived_at",
}

SQLITE_ONLY_PATTERNS = [
    r"\bAUTOINCREMENT\b",
    r"\bPRAGMA\b",
    r"\bsqlite_",
    r"\bWITHOUT\s+ROWID\b",
    r"`",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default=os.environ.get("QUANTGYM_DB", str(DEFAULT_DB)), help="SQLite DB path to inspect.")
    parser.add_argument("--schema", default=str(DEFAULT_SCHEMA), help="Postgres schema.sql path.")
    parser.add_argument("--export", default="", help="Optional JSON export generated by scripts/export-api-sqlite.py.")
    parser.add_argument("--require-db", action="store_true", help="Fail if the SQLite DB file is missing.")
    parser.add_argument("--require-sensitive-export", action="store_true", help="Fail unless --export is a full include-sensitive export.")
    parser.add_argument("--cutover-complete", action="store_true", help="Require final Postgres cutover signoff evidence for a completed migration.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    db_path = Path(args.db).expanduser()
    schema_path = Path(args.schema).expanduser()
    failures: list[str] = []
    warnings: list[str] = []
    data_checks: dict[str, Any] = {}

    schema_sql = read_text(schema_path, "Postgres schema", failures)
    pg_schema = parse_postgres_schema(schema_sql)
    check_postgres_schema_text(schema_sql, pg_schema, failures)

    if db_path.exists() and db_path.is_file():
        try:
            with sqlite3.connect(f"file:{db_path.resolve()}?mode=ro", uri=True) as conn:
                conn.row_factory = sqlite3.Row
                sqlite_schema = load_sqlite_schema(conn)
                check_schema_coverage(sqlite_schema, pg_schema, failures)
                data_checks = check_sqlite_data(conn, sqlite_schema, failures)
        except sqlite3.Error as exc:
            failures.append(f"SQLite DB is unreadable: {db_path} ({exc})")
    elif db_path.exists() and not db_path.is_file():
        failures.append(f"SQLite DB path is not a file: {db_path}")
    elif args.require_db:
        failures.append(f"SQLite DB is missing: {db_path}")
    else:
        warnings.append(f"SQLite DB is missing, skipped live data shape checks: {db_path}")

    export_check = check_export(
        Path(args.export).expanduser() if args.export else None,
        args.require_sensitive_export,
        pg_schema,
        failures,
        warnings,
    )
    cutover_signoff = check_cutover_signoff(args, db_path, export_check, failures)

    summary = {
        "status": "fail" if failures else "pass",
        "dbPath": str(db_path),
        "dbPresent": db_path.exists(),
        "schemaPath": str(schema_path),
        "postgresTables": sorted(pg_schema["tables"].keys()),
        "postgresIndexes": sorted(pg_schema["indexes"].keys()),
        "dataChecks": data_checks,
        "exportCheck": export_check,
        "cutoverSignoff": cutover_signoff,
        "failures": failures,
        "warnings": warnings,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 1 if failures else 0


def read_text(path: Path, label: str, failures: list[str]) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        failures.append(f"{label} is missing or unreadable: {exc}")
        return ""


def parse_postgres_schema(sql: str) -> dict[str, Any]:
    tables: dict[str, dict[str, Any]] = {}
    indexes: dict[str, dict[str, str]] = {}

    for match in re.finditer(r"CREATE\s+TABLE\s+([a-zA-Z_][\w]*)\s*\((.*?)\);", sql, flags=re.IGNORECASE | re.DOTALL):
        table = match.group(1)
        body = match.group(2)
        columns = {}
        for item in split_sql_items(body):
            stripped = item.strip()
            if not stripped:
                continue
            first = stripped.split(None, 1)[0].lower()
            if first in {"primary", "foreign", "unique", "check", "constraint"} or first.startswith(("primary(", "foreign(", "unique(", "check(")):
                continue
            parts = stripped.split(None, 2)
            if len(parts) >= 2:
                columns[parts[0].strip('"')] = {
                    "type": parts[1].lower(),
                    "definition": stripped,
                }
        tables[table] = {"columns": columns, "sql": match.group(0)}

    for match in re.finditer(r"CREATE\s+INDEX\s+([a-zA-Z_][\w]*)\s+ON\s+([a-zA-Z_][\w]*)\s*\((.*?)\);", sql, flags=re.IGNORECASE | re.DOTALL):
        indexes[match.group(1)] = {
            "table": match.group(2),
            "columns": " ".join(match.group(3).split()),
        }

    return {"tables": tables, "indexes": indexes}


def split_sql_items(body: str) -> list[str]:
    items = []
    current = []
    depth = 0
    in_quote = False
    quote_char = ""
    for char in body:
        if in_quote:
            current.append(char)
            if char == quote_char:
                in_quote = False
            continue
        if char in {"'", '"'}:
            in_quote = True
            quote_char = char
            current.append(char)
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        if char == "," and depth == 0:
            items.append("".join(current))
            current = []
        else:
            current.append(char)
    if current:
        items.append("".join(current))
    return items


def check_postgres_schema_text(sql: str, schema: dict[str, Any], failures: list[str]) -> None:
    if not sql.strip():
        return
    if "BEGIN;" not in sql or "COMMIT;" not in sql:
        failures.append("Postgres schema must be wrapped in BEGIN/COMMIT.")
    for pattern in SQLITE_ONLY_PATTERNS:
        if re.search(pattern, sql, flags=re.IGNORECASE):
            failures.append(f"Postgres schema contains SQLite-only syntax matching {pattern}.")
    if not schema["tables"]:
        failures.append("Postgres schema defines no tables.")
    for table, info in schema["tables"].items():
        for column, column_info in info["columns"].items():
            if column in JSON_COLUMNS and column_info["type"] != "jsonb":
                failures.append(f"{table}.{column} must be jsonb in Postgres schema.")
            if column in TIMESTAMP_COLUMNS and column_info["type"] != "timestamptz":
                failures.append(f"{table}.{column} must be timestamptz in Postgres schema.")


def load_sqlite_schema(conn: sqlite3.Connection) -> dict[str, Any]:
    table_rows = conn.execute(
        """
        SELECT name, sql
        FROM sqlite_master
        WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    index_rows = conn.execute(
        """
        SELECT name, tbl_name, sql
        FROM sqlite_master
        WHERE type = 'index' AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    tables = {}
    for row in table_rows:
        name = str(row["name"])
        columns = {
            str(column["name"]): {
                "type": str(column["type"] or "").lower(),
                "notnull": bool(column["notnull"]),
                "pk": bool(column["pk"]),
            }
            for column in conn.execute(f'PRAGMA table_info("{name}")').fetchall()
        }
        foreign_keys = [
            {
                "from": str(item["from"]),
                "table": str(item["table"]),
                "to": str(item["to"]),
                "on_delete": str(item["on_delete"] or "").lower(),
            }
            for item in conn.execute(f'PRAGMA foreign_key_list("{name}")').fetchall()
        ]
        tables[name] = {"columns": columns, "foreignKeys": foreign_keys, "sql": str(row["sql"] or "")}
    indexes = {
        str(row["name"]): {
            "table": str(row["tbl_name"]),
            "sql": str(row["sql"] or ""),
        }
        for row in index_rows
    }
    return {"tables": tables, "indexes": indexes}


def check_schema_coverage(sqlite_schema: dict[str, Any], pg_schema: dict[str, Any], failures: list[str]) -> None:
    sqlite_tables = set(sqlite_schema["tables"].keys())
    pg_tables = set(pg_schema["tables"].keys())
    if sqlite_tables != pg_tables:
        failures.append(f"Postgres table set mismatch. Missing: {sorted(sqlite_tables - pg_tables)}; extra: {sorted(pg_tables - sqlite_tables)}")

    sqlite_indexes = set(sqlite_schema["indexes"].keys())
    pg_indexes = set(pg_schema["indexes"].keys())
    if sqlite_indexes != pg_indexes:
        failures.append(f"Postgres index set mismatch. Missing: {sorted(sqlite_indexes - pg_indexes)}; extra: {sorted(pg_indexes - sqlite_indexes)}")

    for table in sorted(sqlite_tables & pg_tables):
        sqlite_columns = set(sqlite_schema["tables"][table]["columns"].keys())
        pg_columns = set(pg_schema["tables"][table]["columns"].keys())
        if sqlite_columns != pg_columns:
            failures.append(f"{table} column mismatch. Missing: {sorted(sqlite_columns - pg_columns)}; extra: {sorted(pg_columns - sqlite_columns)}")
        pg_sql = normalize_sql(pg_schema["tables"][table]["sql"])
        for fk in sqlite_schema["tables"][table]["foreignKeys"]:
            fragment = f"references {fk['table']}({fk['to']})"
            if fragment not in pg_sql:
                failures.append(f"{table}.{fk['from']} missing Postgres foreign key {fragment}.")
            if fk["on_delete"] and f"on delete {fk['on_delete']}" not in pg_sql:
                failures.append(f"{table}.{fk['from']} missing ON DELETE {fk['on_delete'].upper()} in Postgres schema.")


def check_sqlite_data(conn: sqlite3.Connection, sqlite_schema: dict[str, Any], failures: list[str]) -> dict[str, Any]:
    integrity = [str(row[0]) for row in conn.execute("PRAGMA integrity_check").fetchall()]
    foreign_key_issues = [dict(row) for row in conn.execute("PRAGMA foreign_key_check").fetchall()]
    if integrity != ["ok"]:
        failures.append(f"SQLite integrity_check failed: {integrity}")
    if foreign_key_issues:
        failures.append(f"SQLite foreign_key_check failed: {foreign_key_issues[:5]}")

    table_counts = {}
    json_columns_checked = 0
    timestamp_columns_checked = 0
    invalid_json = []
    invalid_timestamps = []

    for table, table_info in sqlite_schema["tables"].items():
        count = int(conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] or 0)
        table_counts[table] = count
        for column in table_info["columns"]:
            if column in JSON_COLUMNS:
                json_columns_checked += 1
                for row in conn.execute(f'SELECT "{column}" AS value FROM "{table}" WHERE "{column}" IS NOT NULL'):
                    try:
                        json.loads(row["value"])
                    except (TypeError, json.JSONDecodeError):
                        invalid_json.append({"table": table, "column": column})
                        break
            if column in TIMESTAMP_COLUMNS:
                timestamp_columns_checked += 1
                for row in conn.execute(f'SELECT "{column}" AS value FROM "{table}" WHERE "{column}" IS NOT NULL'):
                    if not is_iso_timestamp(row["value"]):
                        invalid_timestamps.append({"table": table, "column": column, "sample": str(row["value"])[:80]})
                        break

    for item in invalid_json:
        failures.append(f"Invalid JSON in {item['table']}.{item['column']}.")
    for item in invalid_timestamps:
        failures.append(f"Invalid timestamp in {item['table']}.{item['column']}: {item['sample']}")

    return {
        "integrityOk": integrity == ["ok"],
        "foreignKeyOk": not foreign_key_issues,
        "tableCounts": table_counts,
        "jsonColumnsChecked": json_columns_checked,
        "timestampColumnsChecked": timestamp_columns_checked,
        "invalidJson": invalid_json,
        "invalidTimestamps": invalid_timestamps,
    }


def is_iso_timestamp(value: Any) -> bool:
    text = str(value or "").strip()
    if not text:
        return False
    try:
        datetime.fromisoformat(text.replace("Z", "+00:00"))
        return True
    except ValueError:
        return False


def check_cutover_signoff(
    args: argparse.Namespace,
    db_path: Path,
    export_check: dict[str, Any],
    failures: list[str],
) -> dict[str, Any]:
    if not args.cutover_complete:
        return {"required": False}

    export_path = Path(args.export).expanduser() if args.export else None
    import_plan = export_check.get("importPlan") if isinstance(export_check.get("importPlan"), dict) else {}
    import_row_count = as_nonnegative_int(import_plan.get("rowCount")) if import_plan else None
    result: dict[str, Any] = {
        "required": True,
        "targetHost": "",
        "database": "",
        "completedAt": "",
        "evidenceHost": "",
        "appDatabaseActive": False,
        "backupConfirmed": False,
        "sourceDbSha256Prefix": "",
        "exportSha256Prefix": "",
        "importPlanRowCount": import_row_count,
        "targetRowCount": None,
    }

    if not args.require_sensitive_export:
        failures.append("--cutover-complete must be paired with --require-sensitive-export.")
    if not db_path.exists() or not db_path.is_file():
        failures.append("--cutover-complete requires a readable SQLite --db path so the source DB hash can be signed off.")
    if not export_path:
        failures.append("--cutover-complete requires --export pointing at the exact include-sensitive migration input.")
    if export_check.get("provided") is not True:
        failures.append("--cutover-complete requires a provided migration export.")
    if export_check.get("includeSensitive") is not True:
        failures.append("--cutover-complete requires an --include-sensitive export.")
    if export_check.get("summaryOnly") is True:
        failures.append("--cutover-complete cannot use a summary-only export.")
    if export_check.get("fullExport") is not True:
        failures.append("--cutover-complete requires a full, non-truncated export.")
    if import_plan.get("columnShapeOk") is not True or import_plan.get("referencedTablesFirst") is not True:
        failures.append("--cutover-complete requires a valid Postgres import plan.")

    status = require_env("QUANTGYM_POSTGRES_CUTOVER_STATUS", failures)
    if status and status.lower() != "complete":
        failures.append("QUANTGYM_POSTGRES_CUTOVER_STATUS must be complete.")

    target_host = require_env("QUANTGYM_POSTGRES_CUTOVER_TARGET_HOST", failures)
    if target_host:
        validate_target_host("QUANTGYM_POSTGRES_CUTOVER_TARGET_HOST", target_host, failures)
        result["targetHost"] = target_host

    database = require_env("QUANTGYM_POSTGRES_CUTOVER_DATABASE", failures)
    if database:
        validate_plain_label("QUANTGYM_POSTGRES_CUTOVER_DATABASE", database, failures)
        result["database"] = database

    completed_at = require_env("QUANTGYM_POSTGRES_CUTOVER_COMPLETED_AT", failures)
    if completed_at:
        result["completedAt"] = validate_non_future_timestamp("QUANTGYM_POSTGRES_CUTOVER_COMPLETED_AT", completed_at, failures)

    evidence_url = require_env("QUANTGYM_POSTGRES_CUTOVER_EVIDENCE_URL", failures)
    if evidence_url:
        result["evidenceHost"] = validate_https_evidence_url("QUANTGYM_POSTGRES_CUTOVER_EVIDENCE_URL", evidence_url, failures)

    expected_export_sha = require_env("QUANTGYM_POSTGRES_CUTOVER_EXPORT_SHA256", failures)
    export_sha = file_sha256(export_path) if export_path and export_path.is_file() else ""
    if expected_export_sha:
        validate_sha256("QUANTGYM_POSTGRES_CUTOVER_EXPORT_SHA256", expected_export_sha, failures)
        if export_sha and expected_export_sha.lower() != export_sha:
            failures.append("QUANTGYM_POSTGRES_CUTOVER_EXPORT_SHA256 does not match the provided --export file.")
    result["exportSha256Prefix"] = export_sha[:12]

    expected_db_sha = require_env("QUANTGYM_POSTGRES_CUTOVER_SOURCE_DB_SHA256", failures)
    db_sha = file_sha256(db_path) if db_path.is_file() else ""
    if expected_db_sha:
        validate_sha256("QUANTGYM_POSTGRES_CUTOVER_SOURCE_DB_SHA256", expected_db_sha, failures)
        if db_sha and expected_db_sha.lower() != db_sha:
            failures.append("QUANTGYM_POSTGRES_CUTOVER_SOURCE_DB_SHA256 does not match the provided --db file.")
    result["sourceDbSha256Prefix"] = db_sha[:12]

    target_row_count_text = require_env("QUANTGYM_POSTGRES_CUTOVER_TARGET_ROW_COUNT", failures)
    if target_row_count_text:
        target_row_count = parse_nonnegative_int_env("QUANTGYM_POSTGRES_CUTOVER_TARGET_ROW_COUNT", target_row_count_text, failures)
        result["targetRowCount"] = target_row_count
        if import_row_count is not None and target_row_count is not None and target_row_count != import_row_count:
            failures.append("QUANTGYM_POSTGRES_CUTOVER_TARGET_ROW_COUNT must match the include-sensitive export import-plan row count.")

    result["appDatabaseActive"] = require_env_flag("QUANTGYM_POSTGRES_CUTOVER_APP_DATABASE_ACTIVE", failures)
    result["backupConfirmed"] = require_env_flag("QUANTGYM_POSTGRES_CUTOVER_BACKUP_CONFIRMED", failures)
    return result


def require_env(name: str, failures: list[str]) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        failures.append(f"{name} is required for --cutover-complete.")
    elif contains_placeholder(value):
        failures.append(f"{name} must not be a placeholder value.")
    return value


def require_env_flag(name: str, failures: list[str]) -> bool:
    value = require_env(name, failures).lower()
    if not value:
        return False
    if value not in {"1", "true", "yes", "confirmed"}:
        failures.append(f"{name} must be one of 1, true, yes, or confirmed.")
        return False
    return True


def contains_placeholder(value: str) -> bool:
    text = value.strip().lower()
    if not text:
        return True
    placeholder_fragments = [
        "example",
        "placeholder",
        "change-me",
        "changeme",
        "todo",
        "tbd",
        "your-",
        "<",
        ">",
    ]
    return any(fragment in text for fragment in placeholder_fragments)


def validate_target_host(name: str, value: str, failures: list[str]) -> None:
    text = value.strip()
    if "://" in text or "/" in text or "@" in text or "?" in text or "#" in text:
        failures.append(f"{name} must be a host name only, not a database URL or DSN.")
        return
    if contains_unsafe_text(text) or not is_valid_host_name(text):
        failures.append(f"{name} must be a plain DNS hostname or IP address.")
        return
    if is_local_or_private_host(text):
        failures.append(f"{name} must not point at localhost, loopback, or a private network address.")


def validate_plain_label(name: str, value: str, failures: list[str]) -> None:
    text = value.strip()
    if (
        "://" in text
        or "/" in text
        or "@" in text
        or len(text) < 2
        or len(text) > 63
        or contains_unsafe_text(text)
        or not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_-]*", text)
    ):
        failures.append(f"{name} must be a plain non-placeholder database name.")


def validate_non_future_timestamp(name: str, value: str, failures: list[str]) -> str:
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        failures.append(f"{name} must be an ISO timestamp.")
        return ""
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    parsed_utc = parsed.astimezone(timezone.utc)
    if parsed_utc > datetime.now(timezone.utc) + timedelta(minutes=5):
        failures.append(f"{name} must not be in the future.")
    return parsed_utc.isoformat(timespec="seconds").replace("+00:00", "Z")


def validate_https_evidence_url(name: str, value: str, failures: list[str]) -> str:
    parsed = urlparse(value)
    host = (parsed.hostname or "").strip()
    if parsed.scheme.lower() != "https" or not host:
        failures.append(f"{name} must be a non-placeholder HTTPS URL.")
        return host
    if is_local_or_private_host(host):
        failures.append(f"{name} must not point at localhost, loopback, or a private network address.")
    if contains_placeholder(host) or (parsed.path and contains_placeholder(parsed.path)):
        failures.append(f"{name} must not be a placeholder URL.")
    if parsed.username or parsed.password:
        failures.append(f"{name} must not include embedded credentials.")
    if parsed.query or parsed.fragment:
        failures.append(f"{name} must not include query strings or fragments.")
    return host


def contains_unsafe_text(value: str) -> bool:
    return bool(re.search(r"[\s\x00-\x1f\x7f]", value))


def is_valid_host_name(value: str) -> bool:
    host = value.strip().strip("[]").lower()
    if not host:
        return False
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        pass
    if len(host) > 253 or host.startswith(".") or host.endswith(".") or ".." in host:
        return False
    labels = host.split(".")
    return all(re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", label) for label in labels)


def validate_sha256(name: str, value: str, failures: list[str]) -> None:
    if not re.fullmatch(r"[a-fA-F0-9]{64}", value.strip()):
        failures.append(f"{name} must be a 64-character SHA-256 hex digest.")


def parse_nonnegative_int_env(name: str, value: str, failures: list[str]) -> int | None:
    try:
        parsed = int(value, 10)
    except ValueError:
        failures.append(f"{name} must be a non-negative integer.")
        return None
    if parsed < 0:
        failures.append(f"{name} must be a non-negative integer.")
        return None
    return parsed


def is_local_or_private_host(value: str) -> bool:
    host = value.strip().strip("[]").lower()
    if host in {"localhost"} or host.endswith(".localhost") or host.endswith(".local"):
        return True
    try:
        address = ipaddress.ip_address(host)
    except ValueError:
        return False
    if address.version == 6 and getattr(address, "ipv4_mapped", None):
        address = address.ipv4_mapped
    return (
        address.is_loopback
        or address.is_private
        or address.is_link_local
        or address.is_unspecified
    )


def file_sha256(path: Path | None) -> str:
    if not path or not path.is_file():
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def check_export(
    path: Path | None,
    require_sensitive: bool,
    pg_schema: dict[str, Any],
    failures: list[str],
    warnings: list[str],
) -> dict[str, Any]:
    if not path:
        if require_sensitive:
            failures.append("--require-sensitive-export needs --export pointing at a secured include-sensitive export.")
        else:
            warnings.append("No include-sensitive export provided; run scripts/export-api-sqlite.py --include-sensitive only when performing a secured cutover.")
        return {"provided": False}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        failures.append(f"Export is missing or invalid JSON: {exc}")
        return {"provided": True, "path": str(path), "validJson": False}

    include_sensitive = payload.get("includeSensitive") is True
    summary_only = payload.get("summaryOnly") is True
    max_rows_per_table = payload.get("maxRowsPerTable")
    status = payload.get("status")
    tables = payload.get("tables") if isinstance(payload.get("tables"), dict) else {}
    has_rows = any(isinstance(item, dict) and "rows" in item for item in tables.values())
    truncated_tables = find_truncated_export_tables(tables)
    row_count_mismatches = find_row_count_mismatches(tables)
    full_export = max_rows_per_table is None and not truncated_tables and not row_count_mismatches

    if status != "pass":
        failures.append(f"Export status must be pass, got {status!r}.")
    if not include_sensitive:
        failures.append("Migration export must be generated with --include-sensitive; redacted exports cannot seed Postgres.")
    if summary_only:
        failures.append("Migration export must not be --summary-only.")
    if not has_rows:
        failures.append("Migration export must contain table rows.")
    if max_rows_per_table is not None:
        failures.append("Migration export must be a full export; rerun without --max-rows-per-table before seeding Postgres.")
    if truncated_tables:
        failures.append(f"Migration export is truncated for tables: {truncated_tables}.")
    if row_count_mismatches:
        failures.append(f"Migration export row counts do not match exported rows: {row_count_mismatches[:8]}.")

    import_plan = {}
    if include_sensitive and not summary_only and has_rows:
        import_plan = build_import_plan(payload, pg_schema, failures)

    return {
        "provided": True,
        "path": str(path),
        "status": status,
        "includeSensitive": include_sensitive,
        "summaryOnly": summary_only,
        "maxRowsPerTable": max_rows_per_table,
        "hasRows": has_rows,
        "fullExport": full_export,
        "truncatedTables": truncated_tables,
        "rowCountMismatchTables": row_count_mismatches,
        "importPlan": import_plan,
    }


def find_truncated_export_tables(tables: dict[str, Any]) -> list[str]:
    truncated = []
    for table_name, item in sorted(tables.items()):
        if isinstance(item, dict) and item.get("truncated") is True:
            truncated.append(table_name)
    return truncated


def find_row_count_mismatches(tables: dict[str, Any]) -> list[dict[str, Any]]:
    mismatches = []
    for table_name, item in sorted(tables.items()):
        if not isinstance(item, dict) or "rows" not in item:
            continue
        rows = item.get("rows")
        if not isinstance(rows, list):
            continue
        row_count = as_nonnegative_int(item.get("rowCount"))
        exported_rows = as_nonnegative_int(item.get("exportedRows"))
        actual_rows = len(rows)
        expected_rows = row_count if row_count is not None else exported_rows
        if exported_rows is not None and exported_rows != actual_rows:
            mismatches.append(
                {
                    "table": table_name,
                    "rowCount": row_count,
                    "exportedRows": exported_rows,
                    "actualRows": actual_rows,
                }
            )
            continue
        if expected_rows is not None and expected_rows != actual_rows:
            mismatches.append(
                {
                    "table": table_name,
                    "rowCount": row_count,
                    "exportedRows": exported_rows,
                    "actualRows": actual_rows,
                }
            )
    return mismatches


def as_nonnegative_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int) and value >= 0:
        return value
    return None


def build_import_plan(payload: dict[str, Any], pg_schema: dict[str, Any], failures: list[str]) -> dict[str, Any]:
    tables = payload.get("tables") if isinstance(payload.get("tables"), dict) else {}
    pg_tables = pg_schema.get("tables") or {}
    export_table_names = set(tables.keys())
    pg_table_names = set(pg_tables.keys())
    if export_table_names != pg_table_names:
        failures.append(
            "Migration export table set mismatch. "
            f"Missing: {sorted(pg_table_names - export_table_names)}; extra: {sorted(export_table_names - pg_table_names)}"
        )

    json_values_checked = 0
    timestamp_values_checked = 0
    row_count = 0
    column_shape_ok = True
    row_tables = 0

    for table_name in sorted(pg_table_names & export_table_names):
        rows = tables.get(table_name, {}).get("rows")
        if not isinstance(rows, list):
            failures.append(f"Migration export table {table_name} must contain a rows array.")
            column_shape_ok = False
            continue
        if rows:
            row_tables += 1
        pg_columns = set(pg_tables[table_name]["columns"].keys())
        for index, row in enumerate(rows):
            row_count += 1
            if not isinstance(row, dict):
                failures.append(f"Migration export {table_name}[{index}] must be an object row.")
                column_shape_ok = False
                continue
            row_columns = set(row.keys())
            if row_columns != pg_columns:
                failures.append(
                    f"Migration export {table_name}[{index}] column mismatch. "
                    f"Missing: {sorted(pg_columns - row_columns)}; extra: {sorted(row_columns - pg_columns)}"
                )
                column_shape_ok = False
            for column, value in row.items():
                if column in JSON_COLUMNS and value is not None:
                    json_values_checked += 1
                    try:
                        json.loads(value if isinstance(value, str) else json.dumps(value))
                    except (TypeError, json.JSONDecodeError):
                        failures.append(f"Migration export {table_name}[{index}].{column} is not valid JSON.")
                if column in TIMESTAMP_COLUMNS and value is not None:
                    timestamp_values_checked += 1
                    if not is_iso_timestamp(value):
                        failures.append(f"Migration export {table_name}[{index}].{column} is not an ISO timestamp: {str(value)[:80]}")

    copy_order = topological_table_order(pg_schema)
    referenced_tables_first = referenced_tables_precede_dependents(pg_schema, copy_order)
    if not referenced_tables_first:
        failures.append("Migration import plan does not place referenced tables before dependent tables.")

    return {
        "tableCount": len(pg_table_names),
        "rowTables": row_tables,
        "rowCount": row_count,
        "copyOrder": copy_order,
        "jsonValuesChecked": json_values_checked,
        "timestampValuesChecked": timestamp_values_checked,
        "columnShapeOk": column_shape_ok,
        "referencedTablesFirst": referenced_tables_first,
    }


def table_dependencies(pg_schema: dict[str, Any]) -> dict[str, set[str]]:
    dependencies: dict[str, set[str]] = {}
    for table, info in (pg_schema.get("tables") or {}).items():
        sql = normalize_sql(info.get("sql", ""))
        referenced = set()
        for match in re.finditer(r"references\s+([a-zA-Z_][\w]*)\s*\(", sql):
            parent = match.group(1)
            if parent != table:
                referenced.add(parent)
        dependencies[table] = referenced
    return dependencies


def topological_table_order(pg_schema: dict[str, Any]) -> list[str]:
    dependencies = table_dependencies(pg_schema)
    remaining = {table: set(parents) for table, parents in dependencies.items()}
    order: list[str] = []
    while remaining:
        ready = sorted(table for table, parents in remaining.items() if not (parents & set(remaining.keys())))
        if not ready:
            order.extend(sorted(remaining.keys()))
            break
        for table in ready:
            order.append(table)
            remaining.pop(table, None)
    return order


def referenced_tables_precede_dependents(pg_schema: dict[str, Any], order: list[str]) -> bool:
    positions = {table: index for index, table in enumerate(order)}
    for table, parents in table_dependencies(pg_schema).items():
        for parent in parents:
            if positions.get(parent, -1) > positions.get(table, -1):
                return False
    return True


def normalize_sql(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace('"', "").lower())


if __name__ == "__main__":
    sys.exit(main())
