/* This file is generated by scripts/check-quanty-assets.mjs. Do not edit by hand. */
import hero160 from "../../../../assets/generated/playful-precision/optimized/hero-wave-160.webp";
import hero320 from "../../../../assets/generated/playful-precision/optimized/hero-wave-320.webp";
import hero640 from "../../../../assets/generated/playful-precision/optimized/hero-wave-640.webp";
import trophy160 from "../../../../assets/generated/playful-precision/optimized/trophy-160.webp";
import trophy320 from "../../../../assets/generated/playful-precision/optimized/trophy-320.webp";
import trophy640 from "../../../../assets/generated/playful-precision/optimized/trophy-640.webp";
import calculator160 from "../../../../assets/generated/playful-precision/optimized/calculator-160.webp";
import calculator320 from "../../../../assets/generated/playful-precision/optimized/calculator-320.webp";
import calculator640 from "../../../../assets/generated/playful-precision/optimized/calculator-640.webp";
import teacher160 from "../../../../assets/generated/playful-precision/optimized/teacher-160.webp";
import teacher320 from "../../../../assets/generated/playful-precision/optimized/teacher-320.webp";
import teacher640 from "../../../../assets/generated/playful-precision/optimized/teacher-640.webp";
import fire160 from "../../../../assets/generated/playful-precision/optimized/fire-160.webp";
import fire320 from "../../../../assets/generated/playful-precision/optimized/fire-320.webp";
import fire640 from "../../../../assets/generated/playful-precision/optimized/fire-640.webp";
import laptop160 from "../../../../assets/generated/playful-precision/optimized/laptop-160.webp";
import laptop320 from "../../../../assets/generated/playful-precision/optimized/laptop-320.webp";
import laptop640 from "../../../../assets/generated/playful-precision/optimized/laptop-640.webp";
import levelup160 from "../../../../assets/generated/playful-precision/optimized/levelup-160.webp";
import levelup320 from "../../../../assets/generated/playful-precision/optimized/levelup-320.webp";
import levelup640 from "../../../../assets/generated/playful-precision/optimized/levelup-640.webp";
import happy160 from "../../../../assets/generated/playful-precision/optimized/avatar-happy-160.webp";
import happy320 from "../../../../assets/generated/playful-precision/optimized/avatar-happy-320.webp";
import happy640 from "../../../../assets/generated/playful-precision/optimized/avatar-happy-640.webp";
import focused160 from "../../../../assets/generated/playful-precision/optimized/avatar-focused-160.webp";
import focused320 from "../../../../assets/generated/playful-precision/optimized/avatar-focused-320.webp";
import focused640 from "../../../../assets/generated/playful-precision/optimized/avatar-focused-640.webp";
import wow160 from "../../../../assets/generated/playful-precision/optimized/avatar-wow-160.webp";
import wow320 from "../../../../assets/generated/playful-precision/optimized/avatar-wow-320.webp";
import wow640 from "../../../../assets/generated/playful-precision/optimized/avatar-wow-640.webp";
import wink160 from "../../../../assets/generated/playful-precision/optimized/avatar-wink-160.webp";
import wink320 from "../../../../assets/generated/playful-precision/optimized/avatar-wink-320.webp";
import wink640 from "../../../../assets/generated/playful-precision/optimized/avatar-wink-640.webp";
import interview160 from "../../../../assets/generated/playful-precision/optimized/interview-160.webp";
import interview320 from "../../../../assets/generated/playful-precision/optimized/interview-320.webp";
import interview640 from "../../../../assets/generated/playful-precision/optimized/interview-640.webp";
import oops160 from "../../../../assets/generated/playful-precision/optimized/oops-160.webp";
import oops320 from "../../../../assets/generated/playful-precision/optimized/oops-320.webp";
import oops640 from "../../../../assets/generated/playful-precision/optimized/oops-640.webp";
import poker160 from "../../../../assets/generated/playful-precision/optimized/poker-160.webp";
import poker320 from "../../../../assets/generated/playful-precision/optimized/poker-320.webp";
import poker640 from "../../../../assets/generated/playful-precision/optimized/poker-640.webp";
import search160 from "../../../../assets/generated/playful-precision/optimized/search-160.webp";
import search320 from "../../../../assets/generated/playful-precision/optimized/search-320.webp";
import search640 from "../../../../assets/generated/playful-precision/optimized/search-640.webp";
import sleep160 from "../../../../assets/generated/playful-precision/optimized/sleep-160.webp";
import sleep320 from "../../../../assets/generated/playful-precision/optimized/sleep-320.webp";
import sleep640 from "../../../../assets/generated/playful-precision/optimized/sleep-640.webp";

export type QuantyVariantWidth = 160 | 320 | 640;
export type QuantyAssetCategory = "mascot" | "avatar";

export type QuantyAssetVariant = Readonly<{
  src: string;
  width: QuantyVariantWidth;
  height: number;
}>;

export type QuantyAssetDefinition = Readonly<{
  logicalName: QuantyAssetName;
  role: string;
  category: QuantyAssetCategory;
  intrinsicWidth: number;
  intrinsicHeight: number;
  variants: readonly QuantyAssetVariant[];
}>;

export const QUANTY_ASSET_NAMES = Object.freeze([
  "hero",
  "trophy",
  "calculator",
  "teacher",
  "fire",
  "laptop",
  "levelup",
  "happy",
  "focused",
  "wow",
  "wink",
  "interview",
  "oops",
  "poker",
  "search",
  "sleep",
] as const);

export type QuantyAssetName = (typeof QUANTY_ASSET_NAMES)[number];

export const QUANTY_ASSETS: Readonly<Record<QuantyAssetName, QuantyAssetDefinition>> = Object.freeze({
  hero: Object.freeze({
    logicalName: "hero",
    role: "auth-hero",
    category: "mascot",
    intrinsicWidth: 1114,
    intrinsicHeight: 1412,
    variants: Object.freeze([
      { src: hero160, width: 160, height: 203 },
      { src: hero320, width: 320, height: 406 },
      { src: hero640, width: 640, height: 812 },
    ] as const),
  }),
  trophy: Object.freeze({
    logicalName: "trophy",
    role: "achievement-reward",
    category: "mascot",
    intrinsicWidth: 1113,
    intrinsicHeight: 1414,
    variants: Object.freeze([
      { src: trophy160, width: 160, height: 204 },
      { src: trophy320, width: 320, height: 407 },
      { src: trophy640, width: 640, height: 814 },
    ] as const),
  }),
  calculator: Object.freeze({
    logicalName: "calculator",
    role: "calculator-practice",
    category: "mascot",
    intrinsicWidth: 1112,
    intrinsicHeight: 1415,
    variants: Object.freeze([
      { src: calculator160, width: 160, height: 204 },
      { src: calculator320, width: 320, height: 408 },
      { src: calculator640, width: 640, height: 815 },
    ] as const),
  }),
  teacher: Object.freeze({
    logicalName: "teacher",
    role: "learning-coach",
    category: "mascot",
    intrinsicWidth: 1106,
    intrinsicHeight: 1422,
    variants: Object.freeze([
      { src: teacher160, width: 160, height: 206 },
      { src: teacher320, width: 320, height: 412 },
      { src: teacher640, width: 640, height: 823 },
    ] as const),
  }),
  fire: Object.freeze({
    logicalName: "fire",
    role: "streak-reward",
    category: "mascot",
    intrinsicWidth: 1112,
    intrinsicHeight: 1414,
    variants: Object.freeze([
      { src: fire160, width: 160, height: 204 },
      { src: fire320, width: 320, height: 407 },
      { src: fire640, width: 640, height: 814 },
    ] as const),
  }),
  laptop: Object.freeze({
    logicalName: "laptop",
    role: "workspace-study",
    category: "mascot",
    intrinsicWidth: 1113,
    intrinsicHeight: 1414,
    variants: Object.freeze([
      { src: laptop160, width: 160, height: 204 },
      { src: laptop320, width: 320, height: 407 },
      { src: laptop640, width: 640, height: 814 },
    ] as const),
  }),
  levelup: Object.freeze({
    logicalName: "levelup",
    role: "level-up-reward",
    category: "mascot",
    intrinsicWidth: 1110,
    intrinsicHeight: 1417,
    variants: Object.freeze([
      { src: levelup160, width: 160, height: 205 },
      { src: levelup320, width: 320, height: 409 },
      { src: levelup640, width: 640, height: 818 },
    ] as const),
  }),
  happy: Object.freeze({
    logicalName: "happy",
    role: "avatar-happy",
    category: "avatar",
    intrinsicWidth: 1113,
    intrinsicHeight: 1414,
    variants: Object.freeze([
      { src: happy160, width: 160, height: 204 },
      { src: happy320, width: 320, height: 407 },
      { src: happy640, width: 640, height: 814 },
    ] as const),
  }),
  focused: Object.freeze({
    logicalName: "focused",
    role: "avatar-focused",
    category: "avatar",
    intrinsicWidth: 1112,
    intrinsicHeight: 1415,
    variants: Object.freeze([
      { src: focused160, width: 160, height: 204 },
      { src: focused320, width: 320, height: 408 },
      { src: focused640, width: 640, height: 815 },
    ] as const),
  }),
  wow: Object.freeze({
    logicalName: "wow",
    role: "avatar-surprised",
    category: "avatar",
    intrinsicWidth: 1112,
    intrinsicHeight: 1414,
    variants: Object.freeze([
      { src: wow160, width: 160, height: 204 },
      { src: wow320, width: 320, height: 407 },
      { src: wow640, width: 640, height: 814 },
    ] as const),
  }),
  wink: Object.freeze({
    logicalName: "wink",
    role: "avatar-wink",
    category: "avatar",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: wink160, width: 160, height: 204 },
      { src: wink320, width: 320, height: 408 },
      { src: wink640, width: 640, height: 815 },
    ] as const),
  }),
  interview: Object.freeze({
    logicalName: "interview",
    role: "interview-practice",
    category: "mascot",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: interview160, width: 160, height: 204 },
      { src: interview320, width: 320, height: 408 },
      { src: interview640, width: 640, height: 815 },
    ] as const),
  }),
  oops: Object.freeze({
    logicalName: "oops",
    role: "error-recovery",
    category: "mascot",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: oops160, width: 160, height: 204 },
      { src: oops320, width: 320, height: 408 },
      { src: oops640, width: 640, height: 815 },
    ] as const),
  }),
  poker: Object.freeze({
    logicalName: "poker",
    role: "poker-practice",
    category: "mascot",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: poker160, width: 160, height: 204 },
      { src: poker320, width: 320, height: 408 },
      { src: poker640, width: 640, height: 815 },
    ] as const),
  }),
  search: Object.freeze({
    logicalName: "search",
    role: "search-empty-state",
    category: "mascot",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: search160, width: 160, height: 204 },
      { src: search320, width: 320, height: 408 },
      { src: search640, width: 640, height: 815 },
    ] as const),
  }),
  sleep: Object.freeze({
    logicalName: "sleep",
    role: "idle-empty-state",
    category: "mascot",
    intrinsicWidth: 1100,
    intrinsicHeight: 1400,
    variants: Object.freeze([
      { src: sleep160, width: 160, height: 204 },
      { src: sleep320, width: 320, height: 408 },
      { src: sleep640, width: 640, height: 815 },
    ] as const),
  }),
});
