// Original practice material. Coding answers are references for self-review, not a judge.
const coding = (id, title, titleEn, prompt, promptEn, examples, constraints, solutions, complexity) => ({
  id: `coding-${id}`, kind: 'coding', title, titleEn, prompt, promptEn,
  examples, constraints, solutions, complexity,
});

export const CODING_QUESTIONS = [
  coding('target-pair', '找到目标和的两个下标', 'Find a target-sum pair',
    '给定整数数组 nums 和整数 target，返回两个不同位置的下标 [i, j]，使 nums[i] + nums[j] = target。若有多个答案，返回任意一个；若无答案，返回空数组。不能重复使用同一个位置。',
    'Given an integer array nums and an integer target, return distinct indices [i, j] whose values sum to target. Any valid pair is accepted. Return an empty array if none exists; an index cannot be reused.',
    [{ input: 'nums = [4, 2, 7, 2], target = 4', output: '[1, 3]' }, { input: 'nums = [1, 3], target = 8', output: '[]' }],
    ['0 ≤ nums.length ≤ 100,000', '−10⁹ ≤ nums[i], target ≤ 10⁹'], {
      python: 'def target_pair(nums, target):\n    seen = {}\n    for i, value in enumerate(nums):\n        other = target - value\n        if other in seen:\n            return [seen[other], i]\n        seen[value] = i\n    return []',
      javascript: 'function targetPair(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const other = target - nums[i];\n    if (seen.has(other)) return [seen.get(other), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}',
      cpp: '#include <vector>\n#include <unordered_map>\nusing namespace std;\nvector<int> targetPair(const vector<int>& nums, int target) {\n    unordered_map<long long, int> seen;\n    for (int i = 0; i < (int)nums.size(); ++i) {\n        long long other = (long long)target - nums[i];\n        if (seen.count(other)) return {seen[other], i};\n        seen[nums[i]] = i;\n    }\n    return {};\n}',
    }, 'Time: O(n) expected · Space: O(n)'),
  coding('best-segment', '最大连续区间和', 'Maximum contiguous sum',
    '给定非空整数数组 nums，返回非空连续子数组的最大元素和。只需返回和，不需要返回下标。注意所有元素都为负数的情况。',
    'Given a nonempty integer array nums, return the maximum sum of a nonempty contiguous subarray. Return the sum only. Consider the all-negative case.',
    [{ input: 'nums = [-3, 4, -1, 2, -6, 3]', output: '5' }, { input: 'nums = [-5, -2, -8]', output: '-2' }],
    ['1 ≤ nums.length ≤ 100,000', '−10⁶ ≤ nums[i] ≤ 10⁶; use 64-bit sums in C++'], {
      python: 'def maximum_sum(nums):\n    current = best = nums[0]\n    for value in nums[1:]:\n        current = max(value, current + value)\n        best = max(best, current)\n    return best',
      javascript: 'function maximumSum(nums) {\n  let current = nums[0], best = nums[0];\n  for (let i = 1; i < nums.length; i++) {\n    current = Math.max(nums[i], current + nums[i]);\n    best = Math.max(best, current);\n  }\n  return best;\n}',
      cpp: '#include <vector>\n#include <algorithm>\nusing namespace std;\nlong long maximumSum(const vector<int>& nums) {\n    long long current = nums[0], best = nums[0];\n    for (int i = 1; i < (int)nums.size(); ++i) {\n        current = max((long long)nums[i], current + nums[i]);\n        best = max(best, current);\n    }\n    return best;\n}',
    }, 'Time: O(n) · Space: O(1)'),
  coding('merge-windows', '合并重叠时间区间', 'Merge overlapping intervals',
    '输入若干闭区间 [start, end]，按起点排序后合并所有重叠区间。端点相同也视为重叠。返回按起点升序排列、互不重叠的区间列表。输入可能为空。',
    'Merge a list of closed intervals [start, end]. Intervals sharing an endpoint overlap. Return non-overlapping intervals in increasing start order. The input may be empty.',
    [{ input: 'intervals = [[5, 8], [1, 3], [3, 6], [10, 11]]', output: '[[1, 8], [10, 11]]' }, { input: 'intervals = []', output: '[]' }],
    ['0 ≤ intervals.length ≤ 100,000', '−10⁹ ≤ start ≤ end ≤ 10⁹'], {
      python: 'def merge_intervals(intervals):\n    merged = []\n    for start, end in sorted(intervals):\n        if not merged or start > merged[-1][1]:\n            merged.append([start, end])\n        else:\n            merged[-1][1] = max(merged[-1][1], end)\n    return merged',
      javascript: 'function mergeIntervals(intervals) {\n  const sorted = intervals.map(x => [...x]).sort((a, b) => a[0] - b[0]);\n  const merged = [];\n  for (const [start, end] of sorted) {\n    const last = merged[merged.length - 1];\n    if (!last || start > last[1]) merged.push([start, end]);\n    else last[1] = Math.max(last[1], end);\n  }\n  return merged;\n}',
      cpp: '#include <vector>\n#include <algorithm>\nusing namespace std;\nvector<vector<int>> mergeIntervals(vector<vector<int>> intervals) {\n    sort(intervals.begin(), intervals.end());\n    vector<vector<int>> merged;\n    for (const auto& item : intervals) {\n        if (merged.empty() || item[0] > merged.back()[1])\n            merged.push_back(item);\n        else merged.back()[1] = max(merged.back()[1], item[1]);\n    }\n    return merged;\n}',
    }, 'Time: O(n log n) · Space: O(n), including output'),
  coding('distinct-window', '最长不重复字符片段', 'Longest distinct-character substring',
    '给定仅包含 ASCII 字符的字符串 s，返回不含重复字符的最长连续子串长度。空字符串返回 0。字符区分大小写，空格也算字符。',
    'Given an ASCII string s, return the length of its longest substring without repeated characters. Return 0 for an empty string. Matching is case-sensitive and spaces count as characters.',
    [{ input: 's = "abcaefbb"', output: '5 ("bcaef")' }, { input: 's = ""', output: '0' }],
    ['0 ≤ s.length ≤ 100,000', 'ASCII characters only (codes 0–127)'], {
      python: 'def longest_distinct(s):\n    last = {}\n    left = best = 0\n    for right, char in enumerate(s):\n        left = max(left, last.get(char, -1) + 1)\n        last[char] = right\n        best = max(best, right - left + 1)\n    return best',
      javascript: 'function longestDistinct(s) {\n  const last = new Map();\n  let left = 0, best = 0;\n  for (let right = 0; right < s.length; right++) {\n    left = Math.max(left, (last.get(s[right]) ?? -1) + 1);\n    last.set(s[right], right);\n    best = Math.max(best, right - left + 1);\n  }\n  return best;\n}',
      cpp: '#include <string>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint longestDistinct(const string& s) {\n    vector<int> last(128, -1);\n    int left = 0, best = 0;\n    for (int right = 0; right < (int)s.size(); ++right) {\n        unsigned char ch = s[right];\n        left = max(left, last[ch] + 1);\n        last[ch] = right;\n        best = max(best, right - left + 1);\n    }\n    return best;\n}',
    }, 'Time: O(n) · Space: O(1), bounded ASCII alphabet'),
  coding('rolling-average', '固定窗口移动平均', 'Fixed-window moving averages',
    '给定整数数组 values 和合法窗口大小 k，返回每个长度恰好为 k 的连续窗口的平均值，顺序与窗口从左到右的顺序一致。结果保留浮点数，不做取整。',
    'Given an integer array values and a valid window size k, return the average of each consecutive window of exactly k values from left to right. Return floating-point averages without rounding.',
    [{ input: 'values = [2, 5, 8, 3], k = 2', output: '[3.5, 6.5, 5.5]' }, { input: 'values = [-2], k = 1', output: '[-2.0]' }],
    ['1 ≤ k ≤ values.length ≤ 100,000', '−10⁶ ≤ values[i] ≤ 10⁶; floating-point tolerance: 10⁻⁶'], {
      python: 'def moving_averages(values, k):\n    total = sum(values[:k])\n    result = [total / k]\n    for right in range(k, len(values)):\n        total += values[right] - values[right - k]\n        result.append(total / k)\n    return result',
      javascript: 'function movingAverages(values, k) {\n  let total = 0;\n  for (let i = 0; i < k; i++) total += values[i];\n  const result = [total / k];\n  for (let right = k; right < values.length; right++) {\n    total += values[right] - values[right - k];\n    result.push(total / k);\n  }\n  return result;\n}',
      cpp: '#include <vector>\nusing namespace std;\nvector<double> movingAverages(const vector<int>& values, int k) {\n    long long total = 0;\n    for (int i = 0; i < k; ++i) total += values[i];\n    vector<double> result{(double)total / k};\n    for (int right = k; right < (int)values.size(); ++right) {\n        total += (long long)values[right] - values[right - k];\n        result.push_back((double)total / k);\n    }\n    return result;\n}',
    }, 'Time: O(n) · Extra space: O(1), excluding output'),
  coding('balanced-brackets', '检查括号配对', 'Validate matching brackets',
    '输入仅含六种括号字符 ()[]{} 的字符串，判断所有括号是否按正确顺序闭合。每个右括号必须匹配最近尚未闭合的同类左括号。空字符串视为合法。',
    'Given a string containing only ()[]{}, determine whether all brackets close in the correct order. Each closing bracket must match the most recent unmatched opening bracket. An empty string is valid.',
    [{ input: 's = "{[()]}"', output: 'true' }, { input: 's = "([)]"', output: 'false' }],
    ['0 ≤ s.length ≤ 100,000', 'Only the characters (, ), [, ], {, } occur'], {
      python: 'def balanced_brackets(s):\n    opening = []\n    pairs = {\")\": \"(\", \"]\": \"[\", \"}\": \"{\"}\n    for char in s:\n        if char in pairs:\n            if not opening or opening.pop() != pairs[char]:\n                return False\n        else:\n            opening.append(char)\n    return not opening',
      javascript: 'function balancedBrackets(s) {\n  const stack = [];\n  const pairs = { ")": "(", "]": "[", "}": "{" };\n  for (const ch of s) {\n    if (Object.hasOwn(pairs, ch)) {\n      if (stack.pop() !== pairs[ch]) return false;\n    } else stack.push(ch);\n  }\n  return stack.length === 0;\n}',
      cpp: '#include <string>\n#include <vector>\nusing namespace std;\nbool balancedBrackets(const string& s) {\n    vector<char> stack;\n    for (char ch : s) {\n        if (ch == \'(\' || ch == \'[\' || ch == \'{\') stack.push_back(ch);\n        else {\n            char expected = ch == \')\' ? \'(\' : ch == \']\' ? \'[\' : \'{\';\n            if (stack.empty() || stack.back() != expected) return false;\n            stack.pop_back();\n        }\n    }\n    return stack.empty();\n}',
    }, 'Time: O(n) · Space: O(n)'),
  coding('first-match', '查找第一个匹配位置', 'Find the first matching index',
    '给定按非递减顺序排列的整数数组 nums 和 target，返回 target 第一次出现的下标；若不存在则返回 −1。要求对数时间复杂度，不允许逐个线性扫描。',
    'Given an integer array nums sorted in nondecreasing order and a target, return the first index containing target, or −1 if absent. Use logarithmic time rather than a linear scan.',
    [{ input: 'nums = [1, 2, 2, 2, 5], target = 2', output: '1' }, { input: 'nums = [], target = 3', output: '-1' }],
    ['0 ≤ nums.length ≤ 100,000', '−10⁹ ≤ nums[i], target ≤ 10⁹; nums is sorted'], {
      python: 'def first_match(nums, target):\n    left, right = 0, len(nums)\n    while left < right:\n        mid = (left + right) // 2\n        if nums[mid] < target:\n            left = mid + 1\n        else:\n            right = mid\n    return left if left < len(nums) and nums[left] == target else -1',
      javascript: 'function firstMatch(nums, target) {\n  let left = 0, right = nums.length;\n  while (left < right) {\n    const mid = left + Math.floor((right - left) / 2);\n    if (nums[mid] < target) left = mid + 1;\n    else right = mid;\n  }\n  return left < nums.length && nums[left] === target ? left : -1;\n}',
      cpp: '#include <vector>\nusing namespace std;\nint firstMatch(const vector<int>& nums, int target) {\n    int left = 0, right = nums.size();\n    while (left < right) {\n        int mid = left + (right - left) / 2;\n        if (nums[mid] < target) left = mid + 1;\n        else right = mid;\n    }\n    return left < (int)nums.size() && nums[left] == target ? left : -1;\n}',
    }, 'Time: O(log n) · Space: O(1)'),
  coding('fewest-coins', '最少硬币组合', 'Minimum coin count',
    '给定互不相同的正整数面额 coins，每种面额可无限使用。返回凑出非负金额 amount 所需的最少硬币数；无法凑出时返回 −1，amount 为 0 时返回 0。不能假设贪心算法成立。',
    'Given distinct positive coin denominations coins with unlimited supply, return the fewest coins needed to make amount. Return −1 if impossible, and 0 when amount is 0. Do not assume greedy selection is optimal.',
    [{ input: 'coins = [1, 3, 4], amount = 6', output: '2 (3 + 3)' }, { input: 'coins = [2, 4], amount = 3', output: '-1' }],
    ['1 ≤ coins.length ≤ 30', '1 ≤ coins[i] ≤ 10,000; 0 ≤ amount ≤ 10,000'], {
      python: 'def fewest_coins(coins, amount):\n    dp = [0] + [amount + 1] * amount\n    for value in range(1, amount + 1):\n        for coin in coins:\n            if coin <= value:\n                dp[value] = min(dp[value], dp[value - coin] + 1)\n    return dp[amount] if dp[amount] <= amount else -1',
      javascript: 'function fewestCoins(coins, amount) {\n  const dp = Array(amount + 1).fill(amount + 1);\n  dp[0] = 0;\n  for (let value = 1; value <= amount; value++) {\n    for (const coin of coins) {\n      if (coin <= value) dp[value] = Math.min(dp[value], dp[value - coin] + 1);\n    }\n  }\n  return dp[amount] <= amount ? dp[amount] : -1;\n}',
      cpp: '#include <vector>\n#include <algorithm>\nusing namespace std;\nint fewestCoins(const vector<int>& coins, int amount) {\n    vector<int> dp(amount + 1, amount + 1);\n    dp[0] = 0;\n    for (int value = 1; value <= amount; ++value) {\n        for (int coin : coins) {\n            if (coin <= value) dp[value] = min(dp[value], dp[value - coin] + 1);\n        }\n    }\n    return dp[amount] <= amount ? dp[amount] : -1;\n}',
    }, 'Time: O(amount × coins.length) · Space: O(amount)'),
];

const tech = (id, title, titleEn, prompt, promptEn, reference, referenceEn) => ({ id: `tech-${id}`, kind: 'tech', title, titleEn, prompt, promptEn, reference, referenceEn });

export const TECH_QUESTIONS = [
  tech('two-heads', '连续两个正面', 'Two consecutive heads',
    '不断独立抛一枚公平硬币，直到第一次连续出现两个正面。包括最后两次在内，期望需要抛多少次？请建立状态方程。',
    'Independently toss a fair coin until two consecutive heads first appear. What is the expected total number of tosses? Derive it using state equations.',
    '设 E₀ 为当前没有连续正面的剩余期望，E₁ 为刚出现一个正面的剩余期望。E₀ = 1 + ½E₀ + ½E₁，E₁ = 1 + ½E₀（再出正面即结束）。解得 E₀ = 6、E₁ = 4。每次抛掷独立且正反概率各为 ½。',
    'Let E₀ be the remaining expectation with no trailing head, and E₁ with one trailing head. E₀ = 1 + ½E₀ + ½E₁ and E₁ = 1 + ½E₀. A head from state 1 ends the process. Solving gives E₀ = 6 and E₁ = 4.'),
  tech('base-rate', '检测结果与基础概率', 'A positive test and its base rate',
    '某类缺陷占产品总量 1%。检测对缺陷产品报阳性的概率为 99%，对无缺陷产品误报阳性的概率为 5%。随机抽取一个产品且检测为阳性，它存在缺陷的概率是多少？',
    'A defect affects 1% of products. A test is positive for 99% of defective products and falsely positive for 5% of nondefective products. What is the probability a randomly selected positive product is defective?',
    '由贝叶斯公式，P(缺陷|阳性) = 0.99×0.01 / (0.99×0.01 + 0.05×0.99) = 1/6 ≈ 16.67%。分母包含真阳性和假阳性；不能将灵敏度 99% 直接当成阳性后的缺陷概率。',
    'Bayes’ rule gives (0.99×0.01)/(0.99×0.01 + 0.05×0.99) = 1/6 ≈ 16.67%. The denominator includes both true and false positives. Sensitivity is not the posterior probability of a defect.'),
  tech('uniform-min', '均匀样本的最小值', 'Minimum of uniform samples',
    'X₁,…,Xₙ 相互独立且服从 Uniform(0,1)，n 为正整数。推导 M = min(X₁,…,Xₙ) 的分布函数与期望。',
    'Let X₁,…,Xₙ be independent Uniform(0,1) random variables, with positive integer n. Derive the CDF and expectation of their minimum M.',
    '对 0≤m≤1，P(M>m) = ∏P(Xᵢ>m) = (1−m)ⁿ，因此 F_M(m)=1−(1−m)ⁿ。m<0 时为 0，m>1 时为 1。E[M]=∫₀¹P(M>m)dm=1/(n+1)。',
    'For 0≤m≤1, P(M>m)=(1−m)ⁿ by independence, so F_M(m)=1−(1−m)ⁿ. The CDF is 0 below 0 and 1 above 1. Integrating the survival function gives E[M]=∫₀¹(1−m)ⁿ dm=1/(n+1).'),
  tech('correlated-sum', '相关变量的和', 'The sum of correlated variables',
    'X、Y 的均值都为 0，标准差分别为 2 和 3，相关系数为 0.5。求 Var(X+Y)。仅知道它们各自服从正态分布，是否足以保证 X+Y 正态？',
    'X and Y have mean 0, standard deviations 2 and 3, and correlation 0.5. Find Var(X+Y). Do normally distributed marginals alone guarantee that X+Y is normal?',
    'Cov(X,Y)=0.5×2×3=3，所以 Var(X+Y)=4+9+2×3=19。边缘正态并不足以保证和正态；联合正态是一个充分条件，独立正态也是。应明确联合分布假设。',
    'Cov(X,Y)=0.5×2×3=3, so Var(X+Y)=4+9+2×3=19. Normal marginals alone do not guarantee a normal sum. Joint normality is sufficient; independent normal variables are a special case.'),
  tech('ols-unbiased', 'OLS 无偏需要什么', 'When is OLS unbiased?',
    '在线性模型 y=Xβ+ε 中，给出确保 OLS 系数条件无偏的核心假设。误差正态性、同方差性是无偏的必要条件吗？',
    'In y=Xβ+ε, state the core conditions ensuring conditional unbiasedness of OLS coefficients. Are normal errors or homoskedasticity necessary for unbiasedness?',
    '在正确线性设定下，X 满列秩、E[ε|X]=0，且相关期望存在，则 β̂=β+(XᵀX)⁻¹Xᵀε，因此 E[β̂|X]=β。同方差和正态性不是无偏所必需；同方差影响经典效率与标准误公式，正态性支持某些有限样本精确推断。',
    'With a correctly specified linear model, full column rank X, existing expectations, and E[ε|X]=0, β̂=β+(XᵀX)⁻¹Xᵀε implies E[β̂|X]=β. Neither homoskedasticity nor normality is required for unbiasedness. They support classical efficiency/variance formulas or exact finite-sample inference.'),
  tech('clt', '中心极限定理的边界', 'The scope of the CLT',
    '陈述独立同分布版本的中心极限定理。它是否意味着任意数据的样本均值在 n=30 时都可以安全地按正态分布处理？说明一个限制。',
    'State the IID central limit theorem. Does it guarantee a reliable normal approximation for any sample mean at n=30? Explain a limitation.',
    '若 Xᵢ IID、均值 μ 存在且方差 0<σ²<∞，则 √n(X̄−μ)/σ 依分布收敛至 N(0,1)。n=30 不是普遍保证；重尾或严重偏态可能收敛很慢，无限方差不满足此版本假设，序列相关还需额外条件。',
    'For IID Xᵢ with finite mean μ and variance 0<σ²<∞, √n(X̄−μ)/σ converges in distribution to N(0,1). There is no universal n=30 guarantee. Skewness and heavy tails can make convergence slow; infinite variance violates this version, and dependence requires other conditions.'),
  tech('dice-maximum', '两枚骰子的最大值', 'The maximum of two dice',
    '独立掷两枚公平六面骰子，令 M 为两次点数的最大值。求 E[M]，并说明如何得到 M 的概率质量函数。',
    'Roll two independent fair six-sided dice and let M be the larger result. Find E[M] and derive its probability mass function.',
    'P(M≤k)=(k/6)²，k=1,…,6，所以 P(M=k)=(k²−(k−1)²)/36=(2k−1)/36。E[M]=Σ k(2k−1)/36=161/36≈4.4722。',
    'For k=1,…,6, P(M≤k)=(k/6)². Thus P(M=k)=(2k−1)/36 and E[M]=Σ k(2k−1)/36=161/36≈4.4722.'),
  tech('random-walk', '公平随机游走的退出概率', 'Fair random-walk exit probability',
    '资金从整数 i 开始，每局独立以相同概率加 1 或减 1，在首次到达 0 或 N 时停止，其中 0<i<N。先到 N 的概率和期望局数分别是多少？',
    'Start with integer capital i. Each independent step adds or subtracts 1 with equal probability. Stop upon first reaching 0 or N, where 0<i<N. What are the probability of hitting N first and the expected number of steps?',
    '命中概率 pᵢ 满足 pᵢ=(pᵢ₋₁+pᵢ₊₁)/2，边界 p₀=0、p_N=1，解为 i/N。期望 Tᵢ 满足 Tᵢ=1+(Tᵢ₋₁+Tᵢ₊₁)/2，边界均为 0，解为 i(N−i)。',
    'The recurrence pᵢ=(pᵢ₋₁+pᵢ₊₁)/2 with p₀=0 and p_N=1 yields pᵢ=i/N. Expected steps satisfy Tᵢ=1+(Tᵢ₋₁+Tᵢ₊₁)/2 with zero boundary values, yielding Tᵢ=i(N−i).'),
  tech('return-composition', '简单收益与对数收益', 'Simple versus log returns',
    '资产第一期上涨 10%，第二期下跌 10%。两期总简单收益是多少？解释为什么不能直接相加简单收益，以及对数收益如何跨期汇总。',
    'An asset gains 10% in period one and loses 10% in period two. What is its cumulative simple return? Explain how simple and log returns aggregate over time.',
    '总简单收益为 1.1×0.9−1=−1%。简单收益按增长因子相乘：R=∏(1+rₜ)−1。价格为正时，对数收益 gₜ=ln(Pₜ/Pₜ₋₁)，跨期相加得到 ln(P_T/P₀)；此例为 ln(0.99)。',
    'The cumulative simple return is 1.1×0.9−1=−1%. Growth factors multiply: R=∏(1+rₜ)−1. For positive prices, log returns gₜ=ln(Pₜ/Pₜ₋₁) add to ln(P_T/P₀), which here is ln(0.99).'),
  tech('leakage', '回测中的未来信息', 'Future information in a backtest',
    '你要用每天收盘后才公布的指标预测当天收盘到次日收盘的收益。数据表只有日期列，建模时有哪些容易产生未来信息泄露的地方？提出合理验证方案。',
    'You use an indicator published after each day’s close to predict returns from that close to the next close. The dataset has only a date column. Identify leakage risks and propose a sound validation approach.',
    '当天收盘时指标尚不可得，不能假定以该收盘价入场。保存真实发布时间，按可交易时点对齐特征与目标；关注历史修订和成分股幸存者偏差。训练、验证按时间切分，所有预处理仅拟合训练集；重叠标签要隔离或留间隔。执行假设应包含实际可成交时刻、成本和滑点。',
    'The indicator is unavailable at the entry close. Align features and targets to actual release and executable trade timestamps. Handle revisions and survivorship bias. Split chronologically, fit preprocessing only on training data, and isolate overlapping labels where relevant. Model executable entry times, transaction costs, and slippage.'),
  tech('conditional-independence', '零相关是否意味着独立', 'Does zero correlation imply independence?',
    '令 X 服从 Uniform(−1,1)，Y=X²。求 Cov(X,Y)，并判断 X 与 Y 是否独立。零相关在什么常见分布条件下可以推出独立？',
    'Let X be Uniform(−1,1) and Y=X². Find Cov(X,Y) and determine whether X and Y are independent. Under what common distributional condition does zero correlation imply independence?',
    '由对称性 E[X]=0、E[X³]=0，故 Cov(X,X²)=0。但 Y 是 X 的非恒定确定函数，两者不独立。对于联合正态变量，零协方差可推出独立；仅有各自边缘正态还不够。',
    'Symmetry gives E[X]=E[X³]=0, so Cov(X,X²)=0. They are dependent because Y is a nonconstant deterministic function of X. Zero covariance implies independence for jointly normal variables, not merely normally distributed marginals.'),
  tech('portfolio-variance', '双资产组合方差', 'Two-asset portfolio variance',
    '资产收益 X、Y 的方差为 σ₁²、σ₂²，协方差为 c。组合收益为 wX+(1−w)Y。写出组合方差，并在 σ₁²+σ₂²−2c>0、允许卖空时求最小方差权重 w。',
    'Asset returns X and Y have variances σ₁² and σ₂² and covariance c. Derive the variance of wX+(1−w)Y and its minimizing w when σ₁²+σ₂²−2c>0 and shorting is allowed.',
    'V(w)=w²σ₁²+(1−w)²σ₂²+2w(1−w)c。对 w 求导并置零，w*=(σ₂²−c)/(σ₁²+σ₂²−2c)。分母为 Var(X−Y)>0，保证严格凸。若禁止卖空且只要求 0≤w≤1，则将该解截断到 [0,1]。',
    'V(w)=w²σ₁²+(1−w)²σ₂²+2w(1−w)c. Differentiating yields w*=(σ₂²−c)/(σ₁²+σ₂²−2c). The denominator is Var(X−Y)>0, ensuring strict convexity. With a 0≤w≤1 constraint, clamp the solution to that interval.'),
];

const behavioral = (id, title, titleEn, prompt, promptEn, reference, referenceEn) => ({ id: `behavioral-${id}`, kind: 'behavioral', title, titleEn, prompt, promptEn, reference, referenceEn });

export const BEHAVIORAL_QUESTIONS = [
  behavioral('failure', '一次失败与调整', 'A failure and what changed', '讲述一次你投入较多但结果不理想的经历。你的具体责任是什么？如何找到原因，之后改变了什么？请使用真实经历。', 'Describe a real effort that fell short despite substantial work. What were you responsible for, how did you diagnose the cause, and what changed afterward?', '自评要点：用简短背景交代目标；明确自己的决策与责任；说明如何依据证据分析原因；给出具体改进和后续验证。避免将责任全部归咎于团队，也不必把失败包装成完美结局。', 'Review your answer for a clear goal, your own decisions and responsibility, evidence-based diagnosis, specific changes, and how you checked whether they helped. Avoid shifting all blame or inventing a perfect outcome.'),
  behavioral('disagreement', '与同伴意见不一致', 'A disagreement with a teammate', '回忆一次你与同伴在分析方法或决策上有实质分歧的情况。你如何确认双方的假设、推动决策，并维护合作关系？', 'Describe a substantive disagreement with a teammate over an analytical method or decision. How did you examine assumptions, reach a decision, and preserve collaboration?', '自评要点：说明真实分歧及各方理由；区分事实与偏好；描述你本人如何倾听、检验假设和提出可执行方案；交代最终决定与结果；说明你可能改变了哪些看法。', 'Cover the real disagreement and each side’s rationale. Separate facts from preferences. Explain your listening, hypothesis testing, and proposed actions, then the decision, result, and any view you revised.'),
  behavioral('ambiguity', '在信息不全时推进', 'Moving forward with ambiguity', '讲述一个目标或信息不完整的项目。你如何识别关键未知、设定优先级，并决定何时行动而不是继续搜集信息？', 'Describe a project with incomplete goals or information. How did you identify key unknowns, prioritize, and decide when to act instead of gathering more information?', '自评要点：交代限制；指出对结果最敏感的未知；说明如何用小实验或沟通降低不确定性；明确决策标准和停止搜集信息的条件；总结结果与仍然存在的限制。', 'Explain the constraints and highest-impact unknowns. Describe small experiments or conversations that reduced uncertainty, decision criteria, when you stopped gathering information, results, and remaining limitations.'),
  behavioral('feedback', '接受一条难听的反馈', 'Responding to difficult feedback', '讲述一次起初让你不舒服、但后来产生帮助的反馈。你如何理解它、采取行动，并判断自己是否真的有所改善？', 'Describe feedback that was initially uncomfortable but later useful. How did you understand it, act on it, and assess whether you improved?', '自评要点：具体说明反馈，避免过于泛泛；承认最初反应但将重点放在后续行动；描述如何澄清期望并练习；给出他人反馈或可观察变化作为证据。', 'Make the feedback specific. Acknowledge your initial reaction but focus on follow-through. Explain how you clarified expectations, practiced, and used follow-up feedback or observable changes to assess improvement.'),
  behavioral('motivation', '为什么选择这个方向', 'Why this role?', '用两分钟说明你为什么申请量化或技术相关岗位。结合一段真实经历，说明你对日常工作内容的理解，以及下一步最想补足的能力。', 'In two minutes, explain why you are applying for a quantitative or technical role. Connect a real experience to your understanding of daily work and one skill you want to develop next.', '自评要点：将动机与做过的具体事情相连接；体现对研究、实现、验证和协作的现实理解；避免只谈薪酬、名气或抽象热爱；具体说明能力缺口与补足行动，不编造公司事实。', 'Connect motivation to something you actually did. Show a realistic understanding of research, implementation, validation, and teamwork. Explain a concrete skill gap and how you are addressing it; avoid inventing employer facts.'),
  behavioral('ownership', '超出职责范围的主动承担', 'Taking ownership beyond your brief', '讲述一次你发现一个没人明确负责的问题并推动解决的经历。你如何判断它值得投入，协调他人，并验证解决方案有效？', 'Describe a problem with no clear owner that you took initiative to solve. How did you decide it mattered, coordinate with others, and validate the solution?', '自评要点：明确问题影响、你的职责边界和主动行为；说明如何得到相关人的配合；给出可验证结果，量化时只用真实数据；反思是否留下可持续的交接或流程。', 'Clarify the impact, your original remit, and your initiative. Explain coordination, verifiable outcomes using only real numbers, and whether you left a sustainable process or handover.'),
  behavioral('priorities', '同时面对多个截止时间', 'Competing deadlines', '讲述一次同时面对多个重要截止时间的经历。你如何比较任务价值、沟通取舍，以及处理无法按原计划完成的部分？', 'Describe a time you faced several important deadlines at once. How did you compare priorities, communicate tradeoffs, and handle work that could not follow the original plan?', '自评要点：说清具体约束和依赖；说明优先级标准；交代什么时候向相关人同步风险，以及如何协商范围；讨论结果与下次会如何改进。', 'Identify constraints and dependencies, explain your prioritization criteria, when you communicated risks, how you negotiated scope, and what the outcome taught you.'),
  behavioral('explanation', '向非技术同事解释分析', 'Explaining analysis to a nontechnical colleague', '讲述一次你需要向没有相关技术背景的人解释复杂分析的经历。你如何选择细节、确认对方理解，并帮助对方做出决定？', 'Describe explaining a complex analysis to someone without the relevant technical background. How did you select details, check understanding, and help them make a decision?', '自评要点：明确听众要做的决定；用具体例子解释关键机制而非堆积术语；交代假设和不确定性；描述如何通过提问或反馈检验理解，并说明沟通结果。', 'Identify the listener’s decision, use a concrete example to explain the mechanism, communicate assumptions and uncertainty, check understanding through questions or feedback, and describe the result.'),
];

export const DAILY_QUESTION_BANK = { tech: TECH_QUESTIONS, coding: CODING_QUESTIONS, behavioral: BEHAVIORAL_QUESTIONS };
