/** Factory deps for createPageApi — extracted from assemblePageApiSlice. */
export function createPageApiDeps(deps) {
  const {
Boolean,
DEFAULT_CLOUD_API_ENDPOINT,
Delete,
JOBS_AUTO_REFRESH_MS,
LLM,
NEWS_AUTO_REFRESH_MS,
PROBLEM_PAGE_SIZE,
PROBLEM_SEARCH_DEBOUNCE_MS,
Queued,
Remove,
Run,
You,
addProblemFromForm,
addProblemFromPayload,
importProblemJsonText,
appState,
appStore,
applyProblemFilterAction,
appendInlineRichText,
authStateRuntime,
authStore,
autoSizeInterviewAnswer,
bindElements,
bindEvents,
bootstrap,
buildProblemProgressItems,
buildRecentContributionHeatmap,
buildTodayStudyPlan,
canUseCloud,
cancel,
clearExperiencePost,
clearForPost,
cloudApi,
cloudConfig,
communityFilterState,
communityStore,
company,
companyDefs,
companyTierFilterState,
companyTierWeight,
computeLeaderboardRankChanges,
confirmShare,
contact,
country,
course,
createCompanyMark,
createCompanyMarkView,
createPageApi,
createdAt,
current,
currentUser,
dayKey,
defaultCloudApiEndpoint,
deleteProblemComment,
deleteSharedWarning,
deleteWarning,
document,
documentRef,
domainStores,
editTitle,
edits,
elements,
els,
emptyBlock,
emptyFiltered,
emptyRecords,
en,
entries,
exitInterview,
experienceLabels,
experienceShareController,
exportInterviewReport,
exportState,
filter,
focusNewsItem,
formatAccountRank,
formatCategoryLabel,
formatCommunityPostDetail,
formatCompanyMeta,
formatCompanySummary,
formatCoursePrompt,
formatCourseSourceTitle,
formatDate,
formatExperienceDate,
formatExperienceOutcome,
formatJobPrompt,
formatNewsDate,
formatNumber,
formatProblemTag,
formatScore,
formatTimeOnly,
generateTodayStudyPlan,
get,
getAllSkillPracticeStats,
getAvailableRouteModules,
getCatalogProblems,
getCloudApiBase,
getCloudConfig,
getCloudSnapshot,
getCompanyJobs,
getCompanyLocationsLabel,
getCompanyOpenRolesLabel,
getCompanyProblemStats,
getCountryLabel,
getCourseQueuedLabel,
getCourseRemoveFromPathLabel,
getCurrentUser,
getCurrentUserName,
getDailyXpSeries,
getDeleteLabel,
getDetailId,
getEmptyReviewLabel,
getEntryCount,
getInitials,
getInterviewAvailableCategories,
getInterviewFavorites,
getInterviewRuntimeState,
getInterviewSelectedCategories,
getInterviewSource,
getLanguage,
getLeaderboardMetricLabel,
getLeaderboardMetricOptions,
getLeaderboardRowsForSettings,
getLeaderboardScopeText,
getLeetcodeHotCompletionStats,
getLibraryEntries,
getLibrarySourceLabel,
getLibrarySubtitle,
getLibraryTitle,
getLlmConfig,
getLocale,
getLocalizedProblemField,
getMessageThreads,
getModuleLifecycle,
getNetworkStatusLabel,
getNotice,
getPage,
getProblemBrowserMatches,
getProblemCollectionEntries,
getProblemCompanies,
getProblemCompletionCount,
getProblemDetailId,
getProblemDetailNavigation,
getProblemDisplayTitle,
getProblemExcerptText,
getProblemFilterState,
getProblemFilterValue,
getProblemMediaMarkdown,
getProblemPage,
getProblemPersonalState,
getProblemSocial,
getProblemSocialNotice,
getProblemSourceLabel,
getProblemThemeEntries,
getQuantScore,
getRank,
getRawLeaderboardSettings,
getRegionLabel,
getSkillPracticeStats,
getSkillScore,
getSnapshot,
getState,
getStreak,
getTotalProblems,
getUserMessageThreads,
getVisibleLibraryEntries,
getWeeklyXp,
goToNextInterviewQuestion,
handleInterviewAnswerKeydown,
handleInterviewTranscriptAction,
handleOnboardingAnswer,
handlePokerDocumentClick,
handlePokerDocumentSubmit,
handlePokerPreflopMatrixClick,
handleProblemCollectionClick,
handleProblemPaginationChange,
handleProblemPaginationClick,
handleProblemPaginationKeydown,
handleProblemPaginationSubmit,
handleProblemSearchInput,
handleProblemSearchKeydown,
handleRouteChange,
hasDurableInterview,
hash,
hashPassword,
hashStringToHue,
heroCoachController,
hideProblemPagination,
history,
importProblemJson,
importState,
inferNewsSourceType,
inferSource,
initGoogleLogin,
initHeroInteractions,
initRouter,
initSharkInteractions,
interviewFocusDefs,
interviewRuntime,
interviewState,
interviewTypeDefs,
isCatalogProblem,
isCurrentOnboardingStep,
isInterviewLiveMode,
isInterviewOnboarding,
isHiddenProblemTag,
isLeetcodeHotExpanded,
isProblemDetailBlockRevealed,
job,
jobsRefreshMs,
keepCurrentLeaderboardRow,
leaderboard,
leaderboardCloudController,
leetcodeHot100,
leetcodeHotController,
leetcodeHotItems,
length,
libraryFilterState,
loadCommunity,
loadInitialPokerGame,
loadPagePartials,
localDateKey,
localResumeReview,
location,
locations,
logout,
makeId,
maybeAutoRefreshJobs,
maybeAutoRefreshNews,
memory,
messageSelectionState,
name,
newTitle,
newsFacade,
newsFilterState,
newsRefreshMs,
normalizeCategory,
normalizeCommunityComment,
normalizeCommunityPost,
normalizeContentSources,
normalizeCountry,
normalizeCourseStates,
normalizeCourses,
normalizeEmail,
normalizeExperience,
normalizeGraduationTerm,
normalizeInterviewExperience,
normalizeJobs,
normalizeLeaderboardSettings,
normalizeLeetcodeHot100Done,
normalizeMessageParticipant,
normalizeMessageThread,
normalizeNetworkContact,
normalizeNewsSkills,
normalizeNewsSourceFilter,
normalizeNewsTopicFilter,
normalizePrepPlan,
normalizeRegionForCountry,
normalizeResources,
normalizeResume,
normalizeResumeState,
normalizeStudyPlan,
open,
openExternalUrl,
openLibraryPractice,
openLibraryReader,
openProblemDetail,
options,
page,
pageLifecycle,
pageLifecycleRef,
parseTags,
path,
pathname,
pokerState,
post,
postId,
postProblemComment,
practiceCompanyProblems,
preferencesStore,
problemDetailState,
problemId,
problemMatchesCompany,
problemMatchesDifficulty,
problemMatchesSource,
problemMatchesTheme,
problemPageSize,
problemPaginationController,
problemSocialState,
problems,
provider,
publishExperience,
publishInterviewExperience,
quantCompanyDefs,
queueCloudSync,
randomChoice,
randomInt,
rebindElements,
recordGameResult,
reflectionLabel,
refreshIcons,
refreshJobs,
refreshJobsFromApi,
refreshLeaderboardCloud,
refreshLeaderboardFromCloud,
refreshNews,
region,
registerFeatureModules,
render,
renderAccountResumeMeta,
renderAll,
renderCloudStatus,
renderCountryOptions,
renderInterviewCategoryPicker,
renderInterviewFavorites,
renderInterviewQuestionPanel,
renderInterviewSetup,
renderInterviewTranscript,
renderLeaderboard,
renderMemory,
renderModules,
renderNewsTicker,
renderNewsTickerForOverview,
renderPokerGame,
renderPokerPreflopChart,
renderProblemPagination,
renderProblems,
renderRegionOptions,
renderRichText,
renderSession,
renderSummary,
renderTodayPlan,
renderTodoDock,
renderTools,
renderUserChip,
replaceState,
requestInterviewHint,
requestResumeReview,
requestResumeReviewFromApi,
resetInterview,
resetPokerTournament,
resetState,
resolveRouteModule,
restartInterviewWithSameConfig,
resumeDurableInterview,
returnToProblemList,
revealInterviewAnswer,
revealProblemDetailBlock,
review,
role,
roles,
runModuleLifecycle,
safeExternalUrl,
save,
saveAccount,
saveAuth,
saveCommunity,
saveCurrentInterviewFavorite,
saveLlmConfig,
saveSettings,
saveSettingsFromValues,
saveState,
scheduleMathTypeset,
search,
selectProblemForInterview,
setInterviewPanelExpandedIndex,
services,
setLanguage,
setPage,
setProblemFilterState,
setProblemPage,
setRawLeaderboardSettings,
settings,
setupButtonRipples,
shareConfirmMessage,
shareCurrentInterviewQuestion,
shareToCommunity,
shouldRenderTools,
showCompanyProblems,
skillDefs,
skillRadarRuntime,
source,
specific,
startDirectMessageWithUser,
startHeroTypewriter,
startInterview,
state,
stores,
submitInterviewAnswer,
summary,
summaryLabel,
switchModule,
syncCloudNow,
t,
the,
title,
to,
toggleDone,
toggleInterviewCategory,
toggleInterviewPanel,
toggleLeetcodeHotDone,
toggleProblemCompleted,
toggleProblemLike,
toggleProblemSaved,
toggleVoiceAnswer,
tools,
topicsLabel,
undoLatestEntry,
updateGlobalSearchPlaceholder,
updateInterviewAnswerFileMeta,
updateInterviewAnswerMode,
updateInterviewLayout,
updateInterviewPdfMeta,
updateInterviewSetupVisibility,
updatePrepTaskIndicator,
updateShare,
updateUnreadMessageBadge,
user,
userState,
userStateRuntime,
userStateStore,
value,
window,
windowRef
  } = deps;

  const isCatalogProblemSafe = typeof isCatalogProblem === "function" ? isCatalogProblem : () => true;
  const getUserProblems = () => Array.isArray(userState.value?.problems) ? userState.value.problems : [];
  const normalizeHotDoneIds = (doneIds, hotItems = leetcodeHot100) => {
    if (typeof normalizeLeetcodeHot100Done === "function") {
      return normalizeLeetcodeHot100Done(doneIds, hotItems);
    }
    const valid = new Set((Array.isArray(hotItems) ? hotItems : []).map((item) => item.id));
    return [...new Set(Array.isArray(doneIds) ? doneIds.map(String) : [])]
      .filter((id) => valid.has(id));
  };

  return {
    appState,
    userState,
    userStateRuntime,
    saveState,
    t,
    getLanguage,
    skillDefs,
    refreshIcons,
    safeExternalUrl,
    openExternalUrl,
    inferSource,
    makeId,
    parseTags,
    formatDate,
    formatNewsDate,
    localDateKey,
    getInitials,
    normalizeCourses,
    normalizeCourseStates,
    normalizeContentSources,
    formatCoursePrompt(course) {
      return `${course.provider} · ${course.summary}`;
    },
    formatCourseSourceTitle(course, source) {
      return `${course.title} · ${source.provider}`;
    },
    getCourseQueuedLabel() {
      return getLanguage() === "en" ? "Queued" : "待学习";
    },
    getCourseRemoveFromPathLabel() {
      return getLanguage() === "en" ? "Remove from path" : "移出路径";
    },
    normalizeJobs,
    refreshJobs: refreshJobsFromApi,
    formatJobPrompt(job) {
      return `${job.company} · ${job.location}`;
    },
    normalizeResume: normalizeResumeState,
    requestResumeReview: requestResumeReviewFromApi,
    localResumeReview,
    getEmptyReviewLabel() {
      return getLanguage() === "en"
        ? "Run the review to get role-specific edits."
        : "点击 LLM 修改简历后，这里会显示针对岗位的修改要点。";
    },
    renderAccountResumeMeta,
    normalizeExperience: normalizeInterviewExperience,
    formatExperienceOutcome,
    formatExperienceDate,
    experienceLabels: {
      newTitle: "新建面经",
      editTitle: "编辑面经",
      emptyFiltered: "当前筛选下还没有面经。",
      emptyRecords: "还没有面经记录。完成一次轮次后，把过程与下一步训练记下来。",
      summaryLabel: "流程概览",
      topicsLabel: "考察主题",
      reflectionLabel: "复盘与下一步",
      updateShare: "更新社群分享",
      shareToCommunity: "分享至社群",
      shareConfirmMessage: "确认已移除受保密要求约束的原题、姓名和联系方式后，再发布到社群。",
      confirmShare: "确认分享",
      cancel: "取消",
      deleteSharedWarning: "删除私有面经不会删除已经发布到社群的分享。确认删除这条私有记录？",
      deleteWarning: "确认删除这条面经记录？"
    },
    publishExperience: publishInterviewExperience,
    messageSelectionState,
    getMessageThreads: getUserMessageThreads,
    loadCommunity,
    saveCommunity,
    normalizeMessageThread,
    normalizeMessageParticipant,
    updateUnreadMessageBadge,
    normalizeNetworkContact,
    getNetworkStatusLabel,
    getDeleteLabel() {
      return getLanguage() === "en" ? "Delete contact" : "删除联系人";
    },
    normalizeResources,
    undoLatestEntry,
    communityFilterState,
    normalizeCommunityPost,
    normalizeCommunityComment,
    clearExperiencePost: (postId) => experienceShareController?.clearForPost?.(postId),
    startDirectMessageWithUser,
    formatCommunityPostDetail(post) {
      return `${getCountryLabel(post.country)} · ${getRegionLabel(post.region)} · ${formatNewsDate(post.createdAt)}`;
    },
    communityStore: domainStores.communityStore,
    normalizeEmail,
    normalizeCountry,
    normalizeRegionForCountry,
    normalizeGraduationTerm,
    hashPassword,
    saveAuth: authStateRuntime.save,
    logout,
    getCurrentUser,
    queueCloudSync,
    renderUserChip,
    renderAll,
    normalizeLeaderboardSettings,
    formatAccountRank(user) {
      return `${getCountryLabel(user.country)} · ${getRegionLabel(user.region)} · ${getRank(getQuantScore())}`;
    },
    getState: () => userState.value,
    buildTodayStudyPlan,
    renderTodayPlan,
    renderTodoDock,
    updatePrepTaskIndicator,
    formatCategoryLabel,
    switchModule,
    elements: els,
    renderProblems,
    getInterviewRuntimeState: () => interviewRuntime.state,
    resetInterview,
    renderInterviewSetup,
    getSkillScore,
    getQuantScore,
    getSkillPracticeStats,
    getAllSkillPracticeStats,
    skillRadarRuntime,
    formatScore,
    randomChoice,
    randomInt,
    normalizeCategory,
    getLocalizedProblemField,
    renderAll,
    libraryFilterState,
    getLibraryEntries,
    getVisibleLibraryEntries,
    getLibraryTitle,
    getLibrarySubtitle,
    openLibraryReader,
    openLibraryPractice,
    getTotalProblems: () => getUserProblems().filter(isCatalogProblemSafe).length,
    canUseCloud,
    cloudApi,
    getCloudApiBase,
    getRawLeaderboardSettings: () => userState.value.leaderboard,
    setRawLeaderboardSettings: (settings) => {
      userState.value.leaderboard = settings;
    },
    normalizeLeaderboardSettings,
    normalizeCountry,
    normalizeRegionForCountry,
    getEntryCount: () => userState.value.entries.length,
    getStreak,
    getWeeklyXp,
    normalizePrepPlan,
    normalizeStudyPlan,
    buildTodayStudyPlan,
    generateTodayStudyPlan,
    getCatalogProblems,
    buildProblemProgressItems,
    getDailyXpSeries,
    buildRecentContributionHeatmap,
    dayKey,
    formatDate: formatNewsDate,
    keepCurrentLeaderboardRow,
    getLeaderboardRowsForSettings,
    computeLeaderboardRankChanges,
    getLeaderboardMetricOptions,
    getLeaderboardScopeText,
    getLeaderboardMetricLabel,
    refreshLeaderboardCloud: refreshLeaderboardFromCloud,
    getCloudSnapshot: () => leaderboardCloudController?.getSnapshot?.() || {},
    startHeroTypewriter,
    initHeroInteractions: () => heroCoachController?.initSharkInteractions?.(),
    focusNewsItem,
    hashStringToHue,
    getCurrentUserName: () => appState.currentUser?.name || "You",
    renderSummary,
    renderMemory: () => getModuleLifecycle("memory")?.render?.(),
    recordGameResult,
    formatNumber,
    elements: els,
    handleProblemSearchInput,
    handleProblemSearchKeydown,
    applyProblemFilterAction,
    handleProblemCollectionClick,
    openProblemDetail,
    returnToProblemList,
    toggleProblemCompleted,
    toggleProblemSaved,
    revealProblemDetailBlock,
    toggleProblemLike,
    postProblemComment,
    addProblemFromForm,
  addProblemFromPayload,
  importProblemJsonText,
    importProblemJson,
    handleProblemPaginationClick,
    handleProblemPaginationSubmit,
    handleProblemPaginationChange,
    handleProblemPaginationKeydown,
    renderProblems,
    getProblemBrowserMatches,
    getProblemFilterState,
    getProblemFilterValue,
    setProblemFilterState,
    getProblemPersonalState,
    getProblemDisplayTitle,
    getProblemExcerptText,
    getProblemSocial,
    getProblemCompanies,
    formatProblemTag,
    isHiddenProblemTag,
    getProblemPage: () => problemPaginationController.getPage(),
    setProblemPage: (page) => problemPaginationController.setPage(page),
    problemPageSize: PROBLEM_PAGE_SIZE,
    searchDebounceMs: PROBLEM_SEARCH_DEBOUNCE_MS,
    getProblemDetailId: () => problemDetailState.getDetailId(),
    setProblemDetailId: (detailId) => problemDetailState.setDetailId(detailId),
    isCatalogProblem,
    getLocale,
    emptyBlock,
    hideProblemPagination,
    renderProblemPagination,
    getProblemDetailNavigation,
    isProblemDetailBlockRevealed,
    getProblemMediaMarkdown,
    renderRichText,
    scheduleMathTypeset,
    selectProblemForInterview,
    deleteProblemComment,
    getProblemSocialNotice: () => problemSocialState.getNotice(),
    getProblemThemeEntries,
    getProblemCollectionEntries,
    getProblemCompletionCount,
    getLeetcodeHotCompletionStats,
    isLeetcodeHotExpanded,
    setLeetcodeHotExpanded: (expanded) => leetcodeHotController?.setExpanded?.(expanded),
    leetcodeHotItems: leetcodeHot100,
    normalizeLeetcodeHot100Done: normalizeHotDoneIds,
    toggleLeetcodeHotDone: (problemId) => leetcodeHotController?.toggleDone?.(problemId),
    buildProblemProgressItems,
    problemMatchesSource,
    problemMatchesCompany,
    problemMatchesTheme,
    problemMatchesDifficulty,
    normalizeCategory,
    companyDefs: quantCompanyDefs,
    getCompanyProblemStats,
    companyTierWeight,
    getProblemSourceLabel: getLibrarySourceLabel,
    interviewState,
    interviewRuntime,
    renderInterviewSetup,
    renderInterviewTranscript,
    renderInterviewFavorites,
    renderInterviewCategoryPicker,
    updateInterviewLayout,
    updateInterviewSetupVisibility,
    updateInterviewAnswerMode,
    renderInterviewQuestionPanel,
    toggleInterviewCategory,
    getInterviewAvailableCategories,
    getInterviewFavorites,
    getInterviewSelectedCategories,
    getInterviewSource,
    hasDurableInterview,
    isInterviewOnboarding,
    isInterviewLiveMode,
    isCurrentOnboardingStep,
    interviewTypeDefs,
    interviewFocusDefs,
    renderRichText,
    appendInlineRichText,
    setInterviewPanelExpandedIndex,
    updateInterviewPdfMeta,
    updateInterviewAnswerFileMeta,
    autoSizeInterviewAnswer,
    handleInterviewAnswerKeydown,
    handleInterviewTranscriptAction,
    handleOnboardingAnswer,
    saveLlmConfig,
    startInterview,
    requestInterviewHint,
    revealInterviewAnswer,
    goToNextInterviewQuestion,
    saveCurrentInterviewFavorite,
    shareCurrentInterviewQuestion,
    restartInterviewWithSameConfig,
    exportInterviewReport,
    toggleInterviewPanel,
    exitInterview,
    resumeDurableInterview,
    toggleVoiceAnswer,
    resetInterview,
    submitInterviewAnswer,
    pokerState,
    loadInitialPokerGame,
    renderPokerGame,
    renderPokerPreflopChart,
    resetPokerTournament,
    handlePokerPreflopMatrixClick,
    rebindElements,
    formatNumber: deps.formatNumber,
    submitPokerAction: deps.submitPokerAction,
    applyPokerQuickBet: deps.applyPokerQuickBet,
    setPokerRaiseAmount: deps.setPokerRaiseAmount,
    takePokerSeat: deps.takePokerSeat,
    sitPokerAtSeat: deps.sitPokerAtSeat,
    addPokerBot: deps.addPokerBot,
    addPokerBotAtSeat: deps.addPokerBotAtSeat,
    fillPokerBots: deps.fillPokerBots,
    removePokerPlayer: deps.removePokerPlayer,
    startPokerTournament: deps.startPokerTournament,
    matchPokerTournament: deps.matchPokerTournament,
    pausePokerGame: deps.pausePokerGame,
    resumePokerGame: deps.resumePokerGame,
    copyPokerRoomLink: deps.copyPokerRoomLink,
    exportPokerSession: deps.exportPokerSession,
    nextPokerHand: deps.nextPokerHand,
    sendPokerChat: deps.sendPokerChat,
    applyPokerSettings: deps.applyPokerSettings,
    handlePokerPlayerAction: deps.handlePokerPlayerAction,
    setPokerMode: deps.setPokerMode,
    getPokerActivePlayers: deps.getPokerActivePlayers,
    getPokerBlindSeats: deps.getPokerBlindSeats,
    getCurrentPokerPlayer: deps.getCurrentPokerPlayer,
    getDefaultPokerPlayerName: deps.getDefaultPokerPlayerName,
    getMinimumPokerRaiseTo: deps.getMinimumPokerRaiseTo,
    getPokerHero: deps.getPokerHero,
    getPokerHeroPreflopCoach: deps.getPokerHeroPreflopCoach,
    getPokerInviteLink: deps.getPokerInviteLink,
    getPokerLedgerRows: deps.getPokerLedgerRows,
    getPokerOnlineLabel: deps.getPokerOnlineLabel,
    getPokerSpectators: deps.getPokerSpectators,
    getPokerStageLabel: deps.getPokerStageLabel,
    getPokerToCall: deps.getPokerToCall,
    getPokerViewerModeLabel: deps.getPokerViewerModeLabel,
    getNextOpenPokerSeat: deps.getNextOpenPokerSeat,
    canPokerRegister: deps.canPokerRegister,
    isPokerHost: deps.isPokerHost,
    isPokerOnlineRoom: deps.isPokerOnlineRoom,
    isPokerSpectator: deps.isPokerSpectator
  };
}
